// Code generated by ent, DO NOT EDIT.

package asset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/imageforge/imageforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUserID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldProjectID, v))
}

// GenerationJobID applies equality check predicate on the "generation_job_id" field. It's identical to GenerationJobIDEQ.
func GenerationJobID(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldGenerationJobID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldDescription, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldPrompt, v))
}

// NegativePrompt applies equality check predicate on the "negative_prompt" field. It's identical to NegativePromptEQ.
func NegativePrompt(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldNegativePrompt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldModel, v))
}

// ModelProvider applies equality check predicate on the "model_provider" field. It's identical to ModelProviderEQ.
func ModelProvider(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldModelProvider, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHeight, v))
}

// AspectRatio applies equality check predicate on the "aspect_ratio" field. It's identical to AspectRatioEQ.
func AspectRatio(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldAspectRatio, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMimeType, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldFileSize, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldStorageKey, v))
}

// ThumbnailKey applies equality check predicate on the "thumbnail_key" field. It's identical to ThumbnailKeyEQ.
func ThumbnailKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldThumbnailKey, v))
}

// MediumKey applies equality check predicate on the "medium_key" field. It's identical to MediumKeyEQ.
func MediumKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMediumKey, v))
}

// CurrentVersion applies equality check predicate on the "current_version" field. It's identical to CurrentVersionEQ.
func CurrentVersion(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCurrentVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldDeletedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldUserID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldProjectID))
}

// GenerationJobIDEQ applies the EQ predicate on the "generation_job_id" field.
func GenerationJobIDEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldGenerationJobID, v))
}

// GenerationJobIDNEQ applies the NEQ predicate on the "generation_job_id" field.
func GenerationJobIDNEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldGenerationJobID, v))
}

// GenerationJobIDIn applies the In predicate on the "generation_job_id" field.
func GenerationJobIDIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldGenerationJobID, vs...))
}

// GenerationJobIDNotIn applies the NotIn predicate on the "generation_job_id" field.
func GenerationJobIDNotIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldGenerationJobID, vs...))
}

// GenerationJobIDIsNil applies the IsNil predicate on the "generation_job_id" field.
func GenerationJobIDIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldGenerationJobID))
}

// GenerationJobIDNotNil applies the NotNil predicate on the "generation_job_id" field.
func GenerationJobIDNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldGenerationJobID))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldSource, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldStatus, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldDescription, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptIsNil applies the IsNil predicate on the "prompt" field.
func PromptIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldPrompt))
}

// PromptNotNil applies the NotNil predicate on the "prompt" field.
func PromptNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldPrompt))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldPrompt, v))
}

// NegativePromptEQ applies the EQ predicate on the "negative_prompt" field.
func NegativePromptEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldNegativePrompt, v))
}

// NegativePromptNEQ applies the NEQ predicate on the "negative_prompt" field.
func NegativePromptNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldNegativePrompt, v))
}

// NegativePromptIn applies the In predicate on the "negative_prompt" field.
func NegativePromptIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldNegativePrompt, vs...))
}

// NegativePromptNotIn applies the NotIn predicate on the "negative_prompt" field.
func NegativePromptNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldNegativePrompt, vs...))
}

// NegativePromptGT applies the GT predicate on the "negative_prompt" field.
func NegativePromptGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldNegativePrompt, v))
}

// NegativePromptGTE applies the GTE predicate on the "negative_prompt" field.
func NegativePromptGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldNegativePrompt, v))
}

// NegativePromptLT applies the LT predicate on the "negative_prompt" field.
func NegativePromptLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldNegativePrompt, v))
}

// NegativePromptLTE applies the LTE predicate on the "negative_prompt" field.
func NegativePromptLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldNegativePrompt, v))
}

// NegativePromptContains applies the Contains predicate on the "negative_prompt" field.
func NegativePromptContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldNegativePrompt, v))
}

// NegativePromptHasPrefix applies the HasPrefix predicate on the "negative_prompt" field.
func NegativePromptHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldNegativePrompt, v))
}

// NegativePromptHasSuffix applies the HasSuffix predicate on the "negative_prompt" field.
func NegativePromptHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldNegativePrompt, v))
}

// NegativePromptIsNil applies the IsNil predicate on the "negative_prompt" field.
func NegativePromptIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldNegativePrompt))
}

// NegativePromptNotNil applies the NotNil predicate on the "negative_prompt" field.
func NegativePromptNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldNegativePrompt))
}

// NegativePromptEqualFold applies the EqualFold predicate on the "negative_prompt" field.
func NegativePromptEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldNegativePrompt, v))
}

// NegativePromptContainsFold applies the ContainsFold predicate on the "negative_prompt" field.
func NegativePromptContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldNegativePrompt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldModel, v))
}

// ModelProviderEQ applies the EQ predicate on the "model_provider" field.
func ModelProviderEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldModelProvider, v))
}

// ModelProviderNEQ applies the NEQ predicate on the "model_provider" field.
func ModelProviderNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldModelProvider, v))
}

// ModelProviderIn applies the In predicate on the "model_provider" field.
func ModelProviderIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldModelProvider, vs...))
}

// ModelProviderNotIn applies the NotIn predicate on the "model_provider" field.
func ModelProviderNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldModelProvider, vs...))
}

// ModelProviderGT applies the GT predicate on the "model_provider" field.
func ModelProviderGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldModelProvider, v))
}

// ModelProviderGTE applies the GTE predicate on the "model_provider" field.
func ModelProviderGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldModelProvider, v))
}

// ModelProviderLT applies the LT predicate on the "model_provider" field.
func ModelProviderLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldModelProvider, v))
}

// ModelProviderLTE applies the LTE predicate on the "model_provider" field.
func ModelProviderLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldModelProvider, v))
}

// ModelProviderContains applies the Contains predicate on the "model_provider" field.
func ModelProviderContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldModelProvider, v))
}

// ModelProviderHasPrefix applies the HasPrefix predicate on the "model_provider" field.
func ModelProviderHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldModelProvider, v))
}

// ModelProviderHasSuffix applies the HasSuffix predicate on the "model_provider" field.
func ModelProviderHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldModelProvider, v))
}

// ModelProviderIsNil applies the IsNil predicate on the "model_provider" field.
func ModelProviderIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldModelProvider))
}

// ModelProviderNotNil applies the NotNil predicate on the "model_provider" field.
func ModelProviderNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldModelProvider))
}

// ModelProviderEqualFold applies the EqualFold predicate on the "model_provider" field.
func ModelProviderEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldModelProvider, v))
}

// ModelProviderContainsFold applies the ContainsFold predicate on the "model_provider" field.
func ModelProviderContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldModelProvider, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldHeight))
}

// AspectRatioEQ applies the EQ predicate on the "aspect_ratio" field.
func AspectRatioEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldAspectRatio, v))
}

// AspectRatioNEQ applies the NEQ predicate on the "aspect_ratio" field.
func AspectRatioNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldAspectRatio, v))
}

// AspectRatioIn applies the In predicate on the "aspect_ratio" field.
func AspectRatioIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldAspectRatio, vs...))
}

// AspectRatioNotIn applies the NotIn predicate on the "aspect_ratio" field.
func AspectRatioNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldAspectRatio, vs...))
}

// AspectRatioGT applies the GT predicate on the "aspect_ratio" field.
func AspectRatioGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldAspectRatio, v))
}

// AspectRatioGTE applies the GTE predicate on the "aspect_ratio" field.
func AspectRatioGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldAspectRatio, v))
}

// AspectRatioLT applies the LT predicate on the "aspect_ratio" field.
func AspectRatioLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldAspectRatio, v))
}

// AspectRatioLTE applies the LTE predicate on the "aspect_ratio" field.
func AspectRatioLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldAspectRatio, v))
}

// AspectRatioContains applies the Contains predicate on the "aspect_ratio" field.
func AspectRatioContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldAspectRatio, v))
}

// AspectRatioHasPrefix applies the HasPrefix predicate on the "aspect_ratio" field.
func AspectRatioHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldAspectRatio, v))
}

// AspectRatioHasSuffix applies the HasSuffix predicate on the "aspect_ratio" field.
func AspectRatioHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldAspectRatio, v))
}

// AspectRatioIsNil applies the IsNil predicate on the "aspect_ratio" field.
func AspectRatioIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldAspectRatio))
}

// AspectRatioNotNil applies the NotNil predicate on the "aspect_ratio" field.
func AspectRatioNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldAspectRatio))
}

// AspectRatioEqualFold applies the EqualFold predicate on the "aspect_ratio" field.
func AspectRatioEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldAspectRatio, v))
}

// AspectRatioContainsFold applies the ContainsFold predicate on the "aspect_ratio" field.
func AspectRatioContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldAspectRatio, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldMimeType))
}

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldMimeType))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldMimeType, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldFileSize, v))
}

// FileSizeIsNil applies the IsNil predicate on the "file_size" field.
func FileSizeIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldFileSize))
}

// FileSizeNotNil applies the NotNil predicate on the "file_size" field.
func FileSizeNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldFileSize))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldStorageKey, v))
}

// ThumbnailKeyEQ applies the EQ predicate on the "thumbnail_key" field.
func ThumbnailKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldThumbnailKey, v))
}

// ThumbnailKeyNEQ applies the NEQ predicate on the "thumbnail_key" field.
func ThumbnailKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldThumbnailKey, v))
}

// ThumbnailKeyIn applies the In predicate on the "thumbnail_key" field.
func ThumbnailKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldThumbnailKey, vs...))
}

// ThumbnailKeyNotIn applies the NotIn predicate on the "thumbnail_key" field.
func ThumbnailKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldThumbnailKey, vs...))
}

// ThumbnailKeyGT applies the GT predicate on the "thumbnail_key" field.
func ThumbnailKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldThumbnailKey, v))
}

// ThumbnailKeyGTE applies the GTE predicate on the "thumbnail_key" field.
func ThumbnailKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldThumbnailKey, v))
}

// ThumbnailKeyLT applies the LT predicate on the "thumbnail_key" field.
func ThumbnailKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldThumbnailKey, v))
}

// ThumbnailKeyLTE applies the LTE predicate on the "thumbnail_key" field.
func ThumbnailKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldThumbnailKey, v))
}

// ThumbnailKeyContains applies the Contains predicate on the "thumbnail_key" field.
func ThumbnailKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldThumbnailKey, v))
}

// ThumbnailKeyHasPrefix applies the HasPrefix predicate on the "thumbnail_key" field.
func ThumbnailKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldThumbnailKey, v))
}

// ThumbnailKeyHasSuffix applies the HasSuffix predicate on the "thumbnail_key" field.
func ThumbnailKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldThumbnailKey, v))
}

// ThumbnailKeyIsNil applies the IsNil predicate on the "thumbnail_key" field.
func ThumbnailKeyIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldThumbnailKey))
}

// ThumbnailKeyNotNil applies the NotNil predicate on the "thumbnail_key" field.
func ThumbnailKeyNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldThumbnailKey))
}

// ThumbnailKeyEqualFold applies the EqualFold predicate on the "thumbnail_key" field.
func ThumbnailKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldThumbnailKey, v))
}

// ThumbnailKeyContainsFold applies the ContainsFold predicate on the "thumbnail_key" field.
func ThumbnailKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldThumbnailKey, v))
}

// MediumKeyEQ applies the EQ predicate on the "medium_key" field.
func MediumKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMediumKey, v))
}

// MediumKeyNEQ applies the NEQ predicate on the "medium_key" field.
func MediumKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldMediumKey, v))
}

// MediumKeyIn applies the In predicate on the "medium_key" field.
func MediumKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldMediumKey, vs...))
}

// MediumKeyNotIn applies the NotIn predicate on the "medium_key" field.
func MediumKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldMediumKey, vs...))
}

// MediumKeyGT applies the GT predicate on the "medium_key" field.
func MediumKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldMediumKey, v))
}

// MediumKeyGTE applies the GTE predicate on the "medium_key" field.
func MediumKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldMediumKey, v))
}

// MediumKeyLT applies the LT predicate on the "medium_key" field.
func MediumKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldMediumKey, v))
}

// MediumKeyLTE applies the LTE predicate on the "medium_key" field.
func MediumKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldMediumKey, v))
}

// MediumKeyContains applies the Contains predicate on the "medium_key" field.
func MediumKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldMediumKey, v))
}

// MediumKeyHasPrefix applies the HasPrefix predicate on the "medium_key" field.
func MediumKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldMediumKey, v))
}

// MediumKeyHasSuffix applies the HasSuffix predicate on the "medium_key" field.
func MediumKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldMediumKey, v))
}

// MediumKeyIsNil applies the IsNil predicate on the "medium_key" field.
func MediumKeyIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldMediumKey))
}

// MediumKeyNotNil applies the NotNil predicate on the "medium_key" field.
func MediumKeyNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldMediumKey))
}

// MediumKeyEqualFold applies the EqualFold predicate on the "medium_key" field.
func MediumKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldMediumKey, v))
}

// MediumKeyContainsFold applies the ContainsFold predicate on the "medium_key" field.
func MediumKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldMediumKey, v))
}

// CurrentVersionEQ applies the EQ predicate on the "current_version" field.
func CurrentVersionEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCurrentVersion, v))
}

// CurrentVersionNEQ applies the NEQ predicate on the "current_version" field.
func CurrentVersionNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldCurrentVersion, v))
}

// CurrentVersionIn applies the In predicate on the "current_version" field.
func CurrentVersionIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldCurrentVersion, vs...))
}

// CurrentVersionNotIn applies the NotIn predicate on the "current_version" field.
func CurrentVersionNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldCurrentVersion, vs...))
}

// CurrentVersionGT applies the GT predicate on the "current_version" field.
func CurrentVersionGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldCurrentVersion, v))
}

// CurrentVersionGTE applies the GTE predicate on the "current_version" field.
func CurrentVersionGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldCurrentVersion, v))
}

// CurrentVersionLT applies the LT predicate on the "current_version" field.
func CurrentVersionLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldCurrentVersion, v))
}

// CurrentVersionLTE applies the LTE predicate on the "current_version" field.
func CurrentVersionLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldCurrentVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldDeletedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGenerationJob applies the HasEdge predicate on the "generation_job" edge.
func HasGenerationJob() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GenerationJobTable, GenerationJobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenerationJobWith applies the HasEdge predicate on the "generation_job" edge with a given conditions (other predicates).
func HasGenerationJobWith(preds ...predicate.GenerationJob) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newGenerationJobStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.AssetVersion) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssetTags applies the HasEdge predicate on the "asset_tags" edge.
func HasAssetTags() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AssetTagsTable, AssetTagsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetTagsWith applies the HasEdge predicate on the "asset_tags" edge with a given conditions (other predicates).
func HasAssetTagsWith(preds ...predicate.AssetTag) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newAssetTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.NotPredicates(p))
}
