// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/imageforge/imageforge/ent/asset"
	"github.com/imageforge/imageforge/ent/assettag"
	"github.com/imageforge/imageforge/ent/tag"
)

// AssetTagCreate is the builder for creating a AssetTag entity.
type AssetTagCreate struct {
	config
	mutation *AssetTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAssetID sets the "asset_id" field.
func (atc *AssetTagCreate) SetAssetID(i int64) *AssetTagCreate {
	atc.mutation.SetAssetID(i)
	return atc
}

// SetTagID sets the "tag_id" field.
func (atc *AssetTagCreate) SetTagID(i int64) *AssetTagCreate {
	atc.mutation.SetTagID(i)
	return atc
}

// SetAsset sets the "asset" edge to the Asset entity.
func (atc *AssetTagCreate) SetAsset(a *Asset) *AssetTagCreate {
	return atc.SetAssetID(a.ID)
}

// SetTag sets the "tag" edge to the Tag entity.
func (atc *AssetTagCreate) SetTag(t *Tag) *AssetTagCreate {
	return atc.SetTagID(t.ID)
}

// Mutation returns the AssetTagMutation object of the builder.
func (atc *AssetTagCreate) Mutation() *AssetTagMutation {
	return atc.mutation
}

// Save creates the AssetTag in the database.
func (atc *AssetTagCreate) Save(ctx context.Context) (*AssetTag, error) {
	return withHooks(ctx, atc.sqlSave, atc.mutation, atc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AssetTagCreate) SaveX(ctx context.Context) *AssetTag {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atc *AssetTagCreate) Exec(ctx context.Context) error {
	_, err := atc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atc *AssetTagCreate) ExecX(ctx context.Context) {
	if err := atc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atc *AssetTagCreate) check() error {
	if _, ok := atc.mutation.AssetID(); !ok {
		return &ValidationError{Name: "asset_id", err: errors.New(`ent: missing required field "AssetTag.asset_id"`)}
	}
	if _, ok := atc.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "AssetTag.tag_id"`)}
	}
	if len(atc.mutation.AssetIDs()) == 0 {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required edge "AssetTag.asset"`)}
	}
	if len(atc.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "AssetTag.tag"`)}
	}
	return nil
}

func (atc *AssetTagCreate) sqlSave(ctx context.Context) (*AssetTag, error) {
	if err := atc.check(); err != nil {
		return nil, err
	}
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	atc.mutation.id = &_node.ID
	atc.mutation.done = true
	return _node, nil
}

func (atc *AssetTagCreate) createSpec() (*AssetTag, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetTag{config: atc.config}
		_spec = sqlgraph.NewCreateSpec(assettag.Table, sqlgraph.NewFieldSpec(assettag.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = atc.conflict
	if nodes := atc.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   assettag.AssetTable,
			Columns: []string{assettag.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := atc.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   assettag.TagTable,
			Columns: []string{assettag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AssetTag.Create().
//		SetAssetID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetTagUpsert) {
//			SetAssetID(v+v).
//		}).
//		Exec(ctx)
func (atc *AssetTagCreate) OnConflict(opts ...sql.ConflictOption) *AssetTagUpsertOne {
	atc.conflict = opts
	return &AssetTagUpsertOne{
		create: atc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AssetTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (atc *AssetTagCreate) OnConflictColumns(columns ...string) *AssetTagUpsertOne {
	atc.conflict = append(atc.conflict, sql.ConflictColumns(columns...))
	return &AssetTagUpsertOne{
		create: atc,
	}
}

type (
	// AssetTagUpsertOne is the builder for "upsert"-ing
	//  one AssetTag node.
	AssetTagUpsertOne struct {
		create *AssetTagCreate
	}

	// AssetTagUpsert is the "OnConflict" setter.
	AssetTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetAssetID sets the "asset_id" field.
func (u *AssetTagUpsert) SetAssetID(v int64) *AssetTagUpsert {
	u.Set(assettag.FieldAssetID, v)
	return u
}

// UpdateAssetID sets the "asset_id" field to the value that was provided on create.
func (u *AssetTagUpsert) UpdateAssetID() *AssetTagUpsert {
	u.SetExcluded(assettag.FieldAssetID)
	return u
}

// SetTagID sets the "tag_id" field.
func (u *AssetTagUpsert) SetTagID(v int64) *AssetTagUpsert {
	u.Set(assettag.FieldTagID, v)
	return u
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *AssetTagUpsert) UpdateTagID() *AssetTagUpsert {
	u.SetExcluded(assettag.FieldTagID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AssetTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AssetTagUpsertOne) UpdateNewValues() *AssetTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AssetTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AssetTagUpsertOne) Ignore() *AssetTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetTagUpsertOne) DoNothing() *AssetTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetTagCreate.OnConflict
// documentation for more info.
func (u *AssetTagUpsertOne) Update(set func(*AssetTagUpsert)) *AssetTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetAssetID sets the "asset_id" field.
func (u *AssetTagUpsertOne) SetAssetID(v int64) *AssetTagUpsertOne {
	return u.Update(func(s *AssetTagUpsert) {
		s.SetAssetID(v)
	})
}

// UpdateAssetID sets the "asset_id" field to the value that was provided on create.
func (u *AssetTagUpsertOne) UpdateAssetID() *AssetTagUpsertOne {
	return u.Update(func(s *AssetTagUpsert) {
		s.UpdateAssetID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *AssetTagUpsertOne) SetTagID(v int64) *AssetTagUpsertOne {
	return u.Update(func(s *AssetTagUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *AssetTagUpsertOne) UpdateTagID() *AssetTagUpsertOne {
	return u.Update(func(s *AssetTagUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *AssetTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AssetTagUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AssetTagUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AssetTagCreateBulk is the builder for creating many AssetTag entities in bulk.
type AssetTagCreateBulk struct {
	config
	err      error
	builders []*AssetTagCreate
	conflict []sql.ConflictOption
}

// Save creates the AssetTag entities in the database.
func (atcb *AssetTagCreateBulk) Save(ctx context.Context) ([]*AssetTag, error) {
	if atcb.err != nil {
		return nil, atcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AssetTag, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = atcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atcb *AssetTagCreateBulk) SaveX(ctx context.Context) []*AssetTag {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atcb *AssetTagCreateBulk) Exec(ctx context.Context) error {
	_, err := atcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atcb *AssetTagCreateBulk) ExecX(ctx context.Context) {
	if err := atcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AssetTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetTagUpsert) {
//			SetAssetID(v+v).
//		}).
//		Exec(ctx)
func (atcb *AssetTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *AssetTagUpsertBulk {
	atcb.conflict = opts
	return &AssetTagUpsertBulk{
		create: atcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AssetTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (atcb *AssetTagCreateBulk) OnConflictColumns(columns ...string) *AssetTagUpsertBulk {
	atcb.conflict = append(atcb.conflict, sql.ConflictColumns(columns...))
	return &AssetTagUpsertBulk{
		create: atcb,
	}
}

// AssetTagUpsertBulk is the builder for "upsert"-ing
// a bulk of AssetTag nodes.
type AssetTagUpsertBulk struct {
	create *AssetTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AssetTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AssetTagUpsertBulk) UpdateNewValues() *AssetTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AssetTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AssetTagUpsertBulk) Ignore() *AssetTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetTagUpsertBulk) DoNothing() *AssetTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetTagCreateBulk.OnConflict
// documentation for more info.
func (u *AssetTagUpsertBulk) Update(set func(*AssetTagUpsert)) *AssetTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetAssetID sets the "asset_id" field.
func (u *AssetTagUpsertBulk) SetAssetID(v int64) *AssetTagUpsertBulk {
	return u.Update(func(s *AssetTagUpsert) {
		s.SetAssetID(v)
	})
}

// UpdateAssetID sets the "asset_id" field to the value that was provided on create.
func (u *AssetTagUpsertBulk) UpdateAssetID() *AssetTagUpsertBulk {
	return u.Update(func(s *AssetTagUpsert) {
		s.UpdateAssetID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *AssetTagUpsertBulk) SetTagID(v int64) *AssetTagUpsertBulk {
	return u.Update(func(s *AssetTagUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *AssetTagUpsertBulk) UpdateTagID() *AssetTagUpsertBulk {
	return u.Update(func(s *AssetTagUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *AssetTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AssetTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
