// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/imageforge/imageforge/ent/asset"
	"github.com/imageforge/imageforge/ent/assettag"
	"github.com/imageforge/imageforge/ent/assetversion"
	"github.com/imageforge/imageforge/ent/generationjob"
	"github.com/imageforge/imageforge/ent/project"
	"github.com/imageforge/imageforge/ent/tag"
	"github.com/imageforge/imageforge/ent/user"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (ac *AssetCreate) SetUserID(i int64) *AssetCreate {
	ac.mutation.SetUserID(i)
	return ac
}

// SetProjectID sets the "project_id" field.
func (ac *AssetCreate) SetProjectID(i int64) *AssetCreate {
	ac.mutation.SetProjectID(i)
	return ac
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (ac *AssetCreate) SetNillableProjectID(i *int64) *AssetCreate {
	if i != nil {
		ac.SetProjectID(*i)
	}
	return ac
}

// SetGenerationJobID sets the "generation_job_id" field.
func (ac *AssetCreate) SetGenerationJobID(i int64) *AssetCreate {
	ac.mutation.SetGenerationJobID(i)
	return ac
}

// SetNillableGenerationJobID sets the "generation_job_id" field if the given value is not nil.
func (ac *AssetCreate) SetNillableGenerationJobID(i *int64) *AssetCreate {
	if i != nil {
		ac.SetGenerationJobID(*i)
	}
	return ac
}

// SetSource sets the "source" field.
func (ac *AssetCreate) SetSource(a asset.Source) *AssetCreate {
	ac.mutation.SetSource(a)
	return ac
}

// SetStatus sets the "status" field.
func (ac *AssetCreate) SetStatus(a asset.Status) *AssetCreate {
	ac.mutation.SetStatus(a)
	return ac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ac *AssetCreate) SetNillableStatus(a *asset.Status) *AssetCreate {
	if a != nil {
		ac.SetStatus(*a)
	}
	return ac
}

// SetTitle sets the "title" field.
func (ac *AssetCreate) SetTitle(s string) *AssetCreate {
	ac.mutation.SetTitle(s)
	return ac
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (ac *AssetCreate) SetNillableTitle(s *string) *AssetCreate {
	if s != nil {
		ac.SetTitle(*s)
	}
	return ac
}

// SetDescription sets the "description" field.
func (ac *AssetCreate) SetDescription(s string) *AssetCreate {
	ac.mutation.SetDescription(s)
	return ac
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ac *AssetCreate) SetNillableDescription(s *string) *AssetCreate {
	if s != nil {
		ac.SetDescription(*s)
	}
	return ac
}

// SetPrompt sets the "prompt" field.
func (ac *AssetCreate) SetPrompt(s string) *AssetCreate {
	ac.mutation.SetPrompt(s)
	return ac
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (ac *AssetCreate) SetNillablePrompt(s *string) *AssetCreate {
	if s != nil {
		ac.SetPrompt(*s)
	}
	return ac
}

// SetNegativePrompt sets the "negative_prompt" field.
func (ac *AssetCreate) SetNegativePrompt(s string) *AssetCreate {
	ac.mutation.SetNegativePrompt(s)
	return ac
}

// SetNillableNegativePrompt sets the "negative_prompt" field if the given value is not nil.
func (ac *AssetCreate) SetNillableNegativePrompt(s *string) *AssetCreate {
	if s != nil {
		ac.SetNegativePrompt(*s)
	}
	return ac
}

// SetModel sets the "model" field.
func (ac *AssetCreate) SetModel(s string) *AssetCreate {
	ac.mutation.SetModel(s)
	return ac
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (ac *AssetCreate) SetNillableModel(s *string) *AssetCreate {
	if s != nil {
		ac.SetModel(*s)
	}
	return ac
}

// SetModelProvider sets the "model_provider" field.
func (ac *AssetCreate) SetModelProvider(s string) *AssetCreate {
	ac.mutation.SetModelProvider(s)
	return ac
}

// SetNillableModelProvider sets the "model_provider" field if the given value is not nil.
func (ac *AssetCreate) SetNillableModelProvider(s *string) *AssetCreate {
	if s != nil {
		ac.SetModelProvider(*s)
	}
	return ac
}

// SetWidth sets the "width" field.
func (ac *AssetCreate) SetWidth(i int) *AssetCreate {
	ac.mutation.SetWidth(i)
	return ac
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (ac *AssetCreate) SetNillableWidth(i *int) *AssetCreate {
	if i != nil {
		ac.SetWidth(*i)
	}
	return ac
}

// SetHeight sets the "height" field.
func (ac *AssetCreate) SetHeight(i int) *AssetCreate {
	ac.mutation.SetHeight(i)
	return ac
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (ac *AssetCreate) SetNillableHeight(i *int) *AssetCreate {
	if i != nil {
		ac.SetHeight(*i)
	}
	return ac
}

// SetAspectRatio sets the "aspect_ratio" field.
func (ac *AssetCreate) SetAspectRatio(s string) *AssetCreate {
	ac.mutation.SetAspectRatio(s)
	return ac
}

// SetNillableAspectRatio sets the "aspect_ratio" field if the given value is not nil.
func (ac *AssetCreate) SetNillableAspectRatio(s *string) *AssetCreate {
	if s != nil {
		ac.SetAspectRatio(*s)
	}
	return ac
}

// SetMimeType sets the "mime_type" field.
func (ac *AssetCreate) SetMimeType(s string) *AssetCreate {
	ac.mutation.SetMimeType(s)
	return ac
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (ac *AssetCreate) SetNillableMimeType(s *string) *AssetCreate {
	if s != nil {
		ac.SetMimeType(*s)
	}
	return ac
}

// SetFileSize sets the "file_size" field.
func (ac *AssetCreate) SetFileSize(i int64) *AssetCreate {
	ac.mutation.SetFileSize(i)
	return ac
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (ac *AssetCreate) SetNillableFileSize(i *int64) *AssetCreate {
	if i != nil {
		ac.SetFileSize(*i)
	}
	return ac
}

// SetStorageKey sets the "storage_key" field.
func (ac *AssetCreate) SetStorageKey(s string) *AssetCreate {
	ac.mutation.SetStorageKey(s)
	return ac
}

// SetThumbnailKey sets the "thumbnail_key" field.
func (ac *AssetCreate) SetThumbnailKey(s string) *AssetCreate {
	ac.mutation.SetThumbnailKey(s)
	return ac
}

// SetNillableThumbnailKey sets the "thumbnail_key" field if the given value is not nil.
func (ac *AssetCreate) SetNillableThumbnailKey(s *string) *AssetCreate {
	if s != nil {
		ac.SetThumbnailKey(*s)
	}
	return ac
}

// SetMediumKey sets the "medium_key" field.
func (ac *AssetCreate) SetMediumKey(s string) *AssetCreate {
	ac.mutation.SetMediumKey(s)
	return ac
}

// SetNillableMediumKey sets the "medium_key" field if the given value is not nil.
func (ac *AssetCreate) SetNillableMediumKey(s *string) *AssetCreate {
	if s != nil {
		ac.SetMediumKey(*s)
	}
	return ac
}

// SetCurrentVersion sets the "current_version" field.
func (ac *AssetCreate) SetCurrentVersion(i int) *AssetCreate {
	ac.mutation.SetCurrentVersion(i)
	return ac
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (ac *AssetCreate) SetNillableCurrentVersion(i *int) *AssetCreate {
	if i != nil {
		ac.SetCurrentVersion(*i)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AssetCreate) SetCreatedAt(t time.Time) *AssetCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AssetCreate) SetNillableCreatedAt(t *time.Time) *AssetCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AssetCreate) SetUpdatedAt(t time.Time) *AssetCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AssetCreate) SetNillableUpdatedAt(t *time.Time) *AssetCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetDeletedAt sets the "deleted_at" field.
func (ac *AssetCreate) SetDeletedAt(t time.Time) *AssetCreate {
	ac.mutation.SetDeletedAt(t)
	return ac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ac *AssetCreate) SetNillableDeletedAt(t *time.Time) *AssetCreate {
	if t != nil {
		ac.SetDeletedAt(*t)
	}
	return ac
}

// SetUser sets the "user" edge to the User entity.
func (ac *AssetCreate) SetUser(u *User) *AssetCreate {
	return ac.SetUserID(u.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (ac *AssetCreate) SetProject(p *Project) *AssetCreate {
	return ac.SetProjectID(p.ID)
}

// SetGenerationJob sets the "generation_job" edge to the GenerationJob entity.
func (ac *AssetCreate) SetGenerationJob(g *GenerationJob) *AssetCreate {
	return ac.SetGenerationJobID(g.ID)
}

// AddVersionIDs adds the "versions" edge to the AssetVersion entity by IDs.
func (ac *AssetCreate) AddVersionIDs(ids ...int64) *AssetCreate {
	ac.mutation.AddVersionIDs(ids...)
	return ac
}

// AddVersions adds the "versions" edges to the AssetVersion entity.
func (ac *AssetCreate) AddVersions(a ...*AssetVersion) *AssetCreate {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ac.AddVersionIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (ac *AssetCreate) AddTagIDs(ids ...int64) *AssetCreate {
	ac.mutation.AddTagIDs(ids...)
	return ac
}

// AddTags adds the "tags" edges to the Tag entity.
func (ac *AssetCreate) AddTags(t ...*Tag) *AssetCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTagIDs(ids...)
}

// AddAssetTagIDs adds the "asset_tags" edge to the AssetTag entity by IDs.
func (ac *AssetCreate) AddAssetTagIDs(ids ...int64) *AssetCreate {
	ac.mutation.AddAssetTagIDs(ids...)
	return ac
}

// AddAssetTags adds the "asset_tags" edges to the AssetTag entity.
func (ac *AssetCreate) AddAssetTags(a ...*AssetTag) *AssetCreate {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ac.AddAssetTagIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (ac *AssetCreate) Mutation() *AssetMutation {
	return ac.mutation
}

// Save creates the Asset in the database.
func (ac *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AssetCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AssetCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AssetCreate) defaults() {
	if _, ok := ac.mutation.Status(); !ok {
		v := asset.DefaultStatus
		ac.mutation.SetStatus(v)
	}
	if _, ok := ac.mutation.CurrentVersion(); !ok {
		v := asset.DefaultCurrentVersion
		ac.mutation.SetCurrentVersion(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := asset.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := asset.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AssetCreate) check() error {
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Asset.user_id"`)}
	}
	if _, ok := ac.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Asset.source"`)}
	}
	if v, ok := ac.mutation.Source(); ok {
		if err := asset.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Asset.source": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Asset.status"`)}
	}
	if v, ok := ac.mutation.Status(); ok {
		if err := asset.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Asset.status": %w`, err)}
		}
	}
	if _, ok := ac.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "Asset.storage_key"`)}
	}
	if v, ok := ac.mutation.StorageKey(); ok {
		if err := asset.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "Asset.storage_key": %w`, err)}
		}
	}
	if _, ok := ac.mutation.CurrentVersion(); !ok {
		return &ValidationError{Name: "current_version", err: errors.New(`ent: missing required field "Asset.current_version"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Asset.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Asset.updated_at"`)}
	}
	if len(ac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Asset.user"`)}
	}
	return nil
}

func (ac *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = ac.conflict
	if value, ok := ac.mutation.Source(); ok {
		_spec.SetField(asset.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := ac.mutation.Status(); ok {
		_spec.SetField(asset.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ac.mutation.Title(); ok {
		_spec.SetField(asset.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := ac.mutation.Description(); ok {
		_spec.SetField(asset.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ac.mutation.Prompt(); ok {
		_spec.SetField(asset.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := ac.mutation.NegativePrompt(); ok {
		_spec.SetField(asset.FieldNegativePrompt, field.TypeString, value)
		_node.NegativePrompt = value
	}
	if value, ok := ac.mutation.Model(); ok {
		_spec.SetField(asset.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := ac.mutation.ModelProvider(); ok {
		_spec.SetField(asset.FieldModelProvider, field.TypeString, value)
		_node.ModelProvider = value
	}
	if value, ok := ac.mutation.Width(); ok {
		_spec.SetField(asset.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := ac.mutation.Height(); ok {
		_spec.SetField(asset.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := ac.mutation.AspectRatio(); ok {
		_spec.SetField(asset.FieldAspectRatio, field.TypeString, value)
		_node.AspectRatio = value
	}
	if value, ok := ac.mutation.MimeType(); ok {
		_spec.SetField(asset.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := ac.mutation.FileSize(); ok {
		_spec.SetField(asset.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := ac.mutation.StorageKey(); ok {
		_spec.SetField(asset.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := ac.mutation.ThumbnailKey(); ok {
		_spec.SetField(asset.FieldThumbnailKey, field.TypeString, value)
		_node.ThumbnailKey = value
	}
	if value, ok := ac.mutation.MediumKey(); ok {
		_spec.SetField(asset.FieldMediumKey, field.TypeString, value)
		_node.MediumKey = value
	}
	if value, ok := ac.mutation.CurrentVersion(); ok {
		_spec.SetField(asset.FieldCurrentVersion, field.TypeInt, value)
		_node.CurrentVersion = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.DeletedAt(); ok {
		_spec.SetField(asset.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := ac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.UserTable,
			Columns: []string{asset.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.ProjectTable,
			Columns: []string{asset.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.GenerationJobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.GenerationJobTable,
			Columns: []string{asset.GenerationJobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GenerationJobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.VersionsTable,
			Columns: []string{asset.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.AssetTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.AssetTagsTable,
			Columns: []string{asset.AssetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Asset.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (ac *AssetCreate) OnConflict(opts ...sql.ConflictOption) *AssetUpsertOne {
	ac.conflict = opts
	return &AssetUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *AssetCreate) OnConflictColumns(columns ...string) *AssetUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &AssetUpsertOne{
		create: ac,
	}
}

type (
	// AssetUpsertOne is the builder for "upsert"-ing
	//  one Asset node.
	AssetUpsertOne struct {
		create *AssetCreate
	}

	// AssetUpsert is the "OnConflict" setter.
	AssetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *AssetUpsert) SetUserID(v int64) *AssetUpsert {
	u.Set(asset.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateUserID() *AssetUpsert {
	u.SetExcluded(asset.FieldUserID)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *AssetUpsert) SetProjectID(v int64) *AssetUpsert {
	u.Set(asset.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateProjectID() *AssetUpsert {
	u.SetExcluded(asset.FieldProjectID)
	return u
}

// ClearProjectID clears the value of the "project_id" field.
func (u *AssetUpsert) ClearProjectID() *AssetUpsert {
	u.SetNull(asset.FieldProjectID)
	return u
}

// SetGenerationJobID sets the "generation_job_id" field.
func (u *AssetUpsert) SetGenerationJobID(v int64) *AssetUpsert {
	u.Set(asset.FieldGenerationJobID, v)
	return u
}

// UpdateGenerationJobID sets the "generation_job_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateGenerationJobID() *AssetUpsert {
	u.SetExcluded(asset.FieldGenerationJobID)
	return u
}

// ClearGenerationJobID clears the value of the "generation_job_id" field.
func (u *AssetUpsert) ClearGenerationJobID() *AssetUpsert {
	u.SetNull(asset.FieldGenerationJobID)
	return u
}

// SetStatus sets the "status" field.
func (u *AssetUpsert) SetStatus(v asset.Status) *AssetUpsert {
	u.Set(asset.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AssetUpsert) UpdateStatus() *AssetUpsert {
	u.SetExcluded(asset.FieldStatus)
	return u
}

// SetTitle sets the "title" field.
func (u *AssetUpsert) SetTitle(v string) *AssetUpsert {
	u.Set(asset.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AssetUpsert) UpdateTitle() *AssetUpsert {
	u.SetExcluded(asset.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *AssetUpsert) ClearTitle() *AssetUpsert {
	u.SetNull(asset.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *AssetUpsert) SetDescription(v string) *AssetUpsert {
	u.Set(asset.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AssetUpsert) UpdateDescription() *AssetUpsert {
	u.SetExcluded(asset.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AssetUpsert) ClearDescription() *AssetUpsert {
	u.SetNull(asset.FieldDescription)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *AssetUpsert) SetPrompt(v string) *AssetUpsert {
	u.Set(asset.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *AssetUpsert) UpdatePrompt() *AssetUpsert {
	u.SetExcluded(asset.FieldPrompt)
	return u
}

// ClearPrompt clears the value of the "prompt" field.
func (u *AssetUpsert) ClearPrompt() *AssetUpsert {
	u.SetNull(asset.FieldPrompt)
	return u
}

// SetNegativePrompt sets the "negative_prompt" field.
func (u *AssetUpsert) SetNegativePrompt(v string) *AssetUpsert {
	u.Set(asset.FieldNegativePrompt, v)
	return u
}

// UpdateNegativePrompt sets the "negative_prompt" field to the value that was provided on create.
func (u *AssetUpsert) UpdateNegativePrompt() *AssetUpsert {
	u.SetExcluded(asset.FieldNegativePrompt)
	return u
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (u *AssetUpsert) ClearNegativePrompt() *AssetUpsert {
	u.SetNull(asset.FieldNegativePrompt)
	return u
}

// SetModel sets the "model" field.
func (u *AssetUpsert) SetModel(v string) *AssetUpsert {
	u.Set(asset.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AssetUpsert) UpdateModel() *AssetUpsert {
	u.SetExcluded(asset.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *AssetUpsert) ClearModel() *AssetUpsert {
	u.SetNull(asset.FieldModel)
	return u
}

// SetModelProvider sets the "model_provider" field.
func (u *AssetUpsert) SetModelProvider(v string) *AssetUpsert {
	u.Set(asset.FieldModelProvider, v)
	return u
}

// UpdateModelProvider sets the "model_provider" field to the value that was provided on create.
func (u *AssetUpsert) UpdateModelProvider() *AssetUpsert {
	u.SetExcluded(asset.FieldModelProvider)
	return u
}

// ClearModelProvider clears the value of the "model_provider" field.
func (u *AssetUpsert) ClearModelProvider() *AssetUpsert {
	u.SetNull(asset.FieldModelProvider)
	return u
}

// SetWidth sets the "width" field.
func (u *AssetUpsert) SetWidth(v int) *AssetUpsert {
	u.Set(asset.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *AssetUpsert) UpdateWidth() *AssetUpsert {
	u.SetExcluded(asset.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *AssetUpsert) AddWidth(v int) *AssetUpsert {
	u.Add(asset.FieldWidth, v)
	return u
}

// ClearWidth clears the value of the "width" field.
func (u *AssetUpsert) ClearWidth() *AssetUpsert {
	u.SetNull(asset.FieldWidth)
	return u
}

// SetHeight sets the "height" field.
func (u *AssetUpsert) SetHeight(v int) *AssetUpsert {
	u.Set(asset.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *AssetUpsert) UpdateHeight() *AssetUpsert {
	u.SetExcluded(asset.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *AssetUpsert) AddHeight(v int) *AssetUpsert {
	u.Add(asset.FieldHeight, v)
	return u
}

// ClearHeight clears the value of the "height" field.
func (u *AssetUpsert) ClearHeight() *AssetUpsert {
	u.SetNull(asset.FieldHeight)
	return u
}

// SetAspectRatio sets the "aspect_ratio" field.
func (u *AssetUpsert) SetAspectRatio(v string) *AssetUpsert {
	u.Set(asset.FieldAspectRatio, v)
	return u
}

// UpdateAspectRatio sets the "aspect_ratio" field to the value that was provided on create.
func (u *AssetUpsert) UpdateAspectRatio() *AssetUpsert {
	u.SetExcluded(asset.FieldAspectRatio)
	return u
}

// ClearAspectRatio clears the value of the "aspect_ratio" field.
func (u *AssetUpsert) ClearAspectRatio() *AssetUpsert {
	u.SetNull(asset.FieldAspectRatio)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *AssetUpsert) SetMimeType(v string) *AssetUpsert {
	u.Set(asset.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AssetUpsert) UpdateMimeType() *AssetUpsert {
	u.SetExcluded(asset.FieldMimeType)
	return u
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AssetUpsert) ClearMimeType() *AssetUpsert {
	u.SetNull(asset.FieldMimeType)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *AssetUpsert) SetFileSize(v int64) *AssetUpsert {
	u.Set(asset.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *AssetUpsert) UpdateFileSize() *AssetUpsert {
	u.SetExcluded(asset.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *AssetUpsert) AddFileSize(v int64) *AssetUpsert {
	u.Add(asset.FieldFileSize, v)
	return u
}

// ClearFileSize clears the value of the "file_size" field.
func (u *AssetUpsert) ClearFileSize() *AssetUpsert {
	u.SetNull(asset.FieldFileSize)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *AssetUpsert) SetStorageKey(v string) *AssetUpsert {
	u.Set(asset.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateStorageKey() *AssetUpsert {
	u.SetExcluded(asset.FieldStorageKey)
	return u
}

// SetThumbnailKey sets the "thumbnail_key" field.
func (u *AssetUpsert) SetThumbnailKey(v string) *AssetUpsert {
	u.Set(asset.FieldThumbnailKey, v)
	return u
}

// UpdateThumbnailKey sets the "thumbnail_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateThumbnailKey() *AssetUpsert {
	u.SetExcluded(asset.FieldThumbnailKey)
	return u
}

// ClearThumbnailKey clears the value of the "thumbnail_key" field.
func (u *AssetUpsert) ClearThumbnailKey() *AssetUpsert {
	u.SetNull(asset.FieldThumbnailKey)
	return u
}

// SetMediumKey sets the "medium_key" field.
func (u *AssetUpsert) SetMediumKey(v string) *AssetUpsert {
	u.Set(asset.FieldMediumKey, v)
	return u
}

// UpdateMediumKey sets the "medium_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateMediumKey() *AssetUpsert {
	u.SetExcluded(asset.FieldMediumKey)
	return u
}

// ClearMediumKey clears the value of the "medium_key" field.
func (u *AssetUpsert) ClearMediumKey() *AssetUpsert {
	u.SetNull(asset.FieldMediumKey)
	return u
}

// SetCurrentVersion sets the "current_version" field.
func (u *AssetUpsert) SetCurrentVersion(v int) *AssetUpsert {
	u.Set(asset.FieldCurrentVersion, v)
	return u
}

// UpdateCurrentVersion sets the "current_version" field to the value that was provided on create.
func (u *AssetUpsert) UpdateCurrentVersion() *AssetUpsert {
	u.SetExcluded(asset.FieldCurrentVersion)
	return u
}

// AddCurrentVersion adds v to the "current_version" field.
func (u *AssetUpsert) AddCurrentVersion(v int) *AssetUpsert {
	u.Add(asset.FieldCurrentVersion, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsert) SetUpdatedAt(v time.Time) *AssetUpsert {
	u.Set(asset.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsert) UpdateUpdatedAt() *AssetUpsert {
	u.SetExcluded(asset.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AssetUpsert) SetDeletedAt(v time.Time) *AssetUpsert {
	u.Set(asset.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AssetUpsert) UpdateDeletedAt() *AssetUpsert {
	u.SetExcluded(asset.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AssetUpsert) ClearDeletedAt() *AssetUpsert {
	u.SetNull(asset.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AssetUpsertOne) UpdateNewValues() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(asset.FieldSource)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(asset.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AssetUpsertOne) Ignore() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetUpsertOne) DoNothing() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetCreate.OnConflict
// documentation for more info.
func (u *AssetUpsertOne) Update(set func(*AssetUpsert)) *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *AssetUpsertOne) SetUserID(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateUserID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUserID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *AssetUpsertOne) SetProjectID(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateProjectID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *AssetUpsertOne) ClearProjectID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearProjectID()
	})
}

// SetGenerationJobID sets the "generation_job_id" field.
func (u *AssetUpsertOne) SetGenerationJobID(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetGenerationJobID(v)
	})
}

// UpdateGenerationJobID sets the "generation_job_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateGenerationJobID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateGenerationJobID()
	})
}

// ClearGenerationJobID clears the value of the "generation_job_id" field.
func (u *AssetUpsertOne) ClearGenerationJobID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearGenerationJobID()
	})
}

// SetStatus sets the "status" field.
func (u *AssetUpsertOne) SetStatus(v asset.Status) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateStatus() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateStatus()
	})
}

// SetTitle sets the "title" field.
func (u *AssetUpsertOne) SetTitle(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateTitle() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *AssetUpsertOne) ClearTitle() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearTitle()
	})
}

// SetDescription sets the "description" field.
func (u *AssetUpsertOne) SetDescription(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateDescription() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AssetUpsertOne) ClearDescription() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDescription()
	})
}

// SetPrompt sets the "prompt" field.
func (u *AssetUpsertOne) SetPrompt(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdatePrompt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdatePrompt()
	})
}

// ClearPrompt clears the value of the "prompt" field.
func (u *AssetUpsertOne) ClearPrompt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearPrompt()
	})
}

// SetNegativePrompt sets the "negative_prompt" field.
func (u *AssetUpsertOne) SetNegativePrompt(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetNegativePrompt(v)
	})
}

// UpdateNegativePrompt sets the "negative_prompt" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateNegativePrompt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateNegativePrompt()
	})
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (u *AssetUpsertOne) ClearNegativePrompt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearNegativePrompt()
	})
}

// SetModel sets the "model" field.
func (u *AssetUpsertOne) SetModel(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateModel() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AssetUpsertOne) ClearModel() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearModel()
	})
}

// SetModelProvider sets the "model_provider" field.
func (u *AssetUpsertOne) SetModelProvider(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetModelProvider(v)
	})
}

// UpdateModelProvider sets the "model_provider" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateModelProvider() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateModelProvider()
	})
}

// ClearModelProvider clears the value of the "model_provider" field.
func (u *AssetUpsertOne) ClearModelProvider() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearModelProvider()
	})
}

// SetWidth sets the "width" field.
func (u *AssetUpsertOne) SetWidth(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *AssetUpsertOne) AddWidth(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateWidth() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *AssetUpsertOne) ClearWidth() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *AssetUpsertOne) SetHeight(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *AssetUpsertOne) AddHeight(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateHeight() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *AssetUpsertOne) ClearHeight() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearHeight()
	})
}

// SetAspectRatio sets the "aspect_ratio" field.
func (u *AssetUpsertOne) SetAspectRatio(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetAspectRatio(v)
	})
}

// UpdateAspectRatio sets the "aspect_ratio" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateAspectRatio() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateAspectRatio()
	})
}

// ClearAspectRatio clears the value of the "aspect_ratio" field.
func (u *AssetUpsertOne) ClearAspectRatio() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearAspectRatio()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *AssetUpsertOne) SetMimeType(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateMimeType() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AssetUpsertOne) ClearMimeType() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMimeType()
	})
}

// SetFileSize sets the "file_size" field.
func (u *AssetUpsertOne) SetFileSize(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *AssetUpsertOne) AddFileSize(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateFileSize() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateFileSize()
	})
}

// ClearFileSize clears the value of the "file_size" field.
func (u *AssetUpsertOne) ClearFileSize() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearFileSize()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *AssetUpsertOne) SetStorageKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateStorageKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateStorageKey()
	})
}

// SetThumbnailKey sets the "thumbnail_key" field.
func (u *AssetUpsertOne) SetThumbnailKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetThumbnailKey(v)
	})
}

// UpdateThumbnailKey sets the "thumbnail_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateThumbnailKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateThumbnailKey()
	})
}

// ClearThumbnailKey clears the value of the "thumbnail_key" field.
func (u *AssetUpsertOne) ClearThumbnailKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearThumbnailKey()
	})
}

// SetMediumKey sets the "medium_key" field.
func (u *AssetUpsertOne) SetMediumKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetMediumKey(v)
	})
}

// UpdateMediumKey sets the "medium_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateMediumKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMediumKey()
	})
}

// ClearMediumKey clears the value of the "medium_key" field.
func (u *AssetUpsertOne) ClearMediumKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMediumKey()
	})
}

// SetCurrentVersion sets the "current_version" field.
func (u *AssetUpsertOne) SetCurrentVersion(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetCurrentVersion(v)
	})
}

// AddCurrentVersion adds v to the "current_version" field.
func (u *AssetUpsertOne) AddCurrentVersion(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddCurrentVersion(v)
	})
}

// UpdateCurrentVersion sets the "current_version" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateCurrentVersion() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateCurrentVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsertOne) SetUpdatedAt(v time.Time) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateUpdatedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AssetUpsertOne) SetDeletedAt(v time.Time) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateDeletedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AssetUpsertOne) ClearDeletedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *AssetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AssetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AssetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
	conflict []sql.ConflictOption
}

// Save creates the Asset entities in the database.
func (acb *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Asset, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Asset.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (acb *AssetCreateBulk) OnConflict(opts ...sql.ConflictOption) *AssetUpsertBulk {
	acb.conflict = opts
	return &AssetUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *AssetCreateBulk) OnConflictColumns(columns ...string) *AssetUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &AssetUpsertBulk{
		create: acb,
	}
}

// AssetUpsertBulk is the builder for "upsert"-ing
// a bulk of Asset nodes.
type AssetUpsertBulk struct {
	create *AssetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AssetUpsertBulk) UpdateNewValues() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(asset.FieldSource)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(asset.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AssetUpsertBulk) Ignore() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetUpsertBulk) DoNothing() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetCreateBulk.OnConflict
// documentation for more info.
func (u *AssetUpsertBulk) Update(set func(*AssetUpsert)) *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *AssetUpsertBulk) SetUserID(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateUserID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUserID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *AssetUpsertBulk) SetProjectID(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateProjectID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *AssetUpsertBulk) ClearProjectID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearProjectID()
	})
}

// SetGenerationJobID sets the "generation_job_id" field.
func (u *AssetUpsertBulk) SetGenerationJobID(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetGenerationJobID(v)
	})
}

// UpdateGenerationJobID sets the "generation_job_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateGenerationJobID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateGenerationJobID()
	})
}

// ClearGenerationJobID clears the value of the "generation_job_id" field.
func (u *AssetUpsertBulk) ClearGenerationJobID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearGenerationJobID()
	})
}

// SetStatus sets the "status" field.
func (u *AssetUpsertBulk) SetStatus(v asset.Status) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateStatus() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateStatus()
	})
}

// SetTitle sets the "title" field.
func (u *AssetUpsertBulk) SetTitle(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateTitle() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *AssetUpsertBulk) ClearTitle() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearTitle()
	})
}

// SetDescription sets the "description" field.
func (u *AssetUpsertBulk) SetDescription(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateDescription() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AssetUpsertBulk) ClearDescription() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDescription()
	})
}

// SetPrompt sets the "prompt" field.
func (u *AssetUpsertBulk) SetPrompt(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdatePrompt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdatePrompt()
	})
}

// ClearPrompt clears the value of the "prompt" field.
func (u *AssetUpsertBulk) ClearPrompt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearPrompt()
	})
}

// SetNegativePrompt sets the "negative_prompt" field.
func (u *AssetUpsertBulk) SetNegativePrompt(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetNegativePrompt(v)
	})
}

// UpdateNegativePrompt sets the "negative_prompt" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateNegativePrompt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateNegativePrompt()
	})
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (u *AssetUpsertBulk) ClearNegativePrompt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearNegativePrompt()
	})
}

// SetModel sets the "model" field.
func (u *AssetUpsertBulk) SetModel(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateModel() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AssetUpsertBulk) ClearModel() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearModel()
	})
}

// SetModelProvider sets the "model_provider" field.
func (u *AssetUpsertBulk) SetModelProvider(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetModelProvider(v)
	})
}

// UpdateModelProvider sets the "model_provider" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateModelProvider() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateModelProvider()
	})
}

// ClearModelProvider clears the value of the "model_provider" field.
func (u *AssetUpsertBulk) ClearModelProvider() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearModelProvider()
	})
}

// SetWidth sets the "width" field.
func (u *AssetUpsertBulk) SetWidth(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *AssetUpsertBulk) AddWidth(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateWidth() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *AssetUpsertBulk) ClearWidth() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *AssetUpsertBulk) SetHeight(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *AssetUpsertBulk) AddHeight(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateHeight() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *AssetUpsertBulk) ClearHeight() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearHeight()
	})
}

// SetAspectRatio sets the "aspect_ratio" field.
func (u *AssetUpsertBulk) SetAspectRatio(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetAspectRatio(v)
	})
}

// UpdateAspectRatio sets the "aspect_ratio" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateAspectRatio() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateAspectRatio()
	})
}

// ClearAspectRatio clears the value of the "aspect_ratio" field.
func (u *AssetUpsertBulk) ClearAspectRatio() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearAspectRatio()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *AssetUpsertBulk) SetMimeType(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateMimeType() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AssetUpsertBulk) ClearMimeType() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMimeType()
	})
}

// SetFileSize sets the "file_size" field.
func (u *AssetUpsertBulk) SetFileSize(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *AssetUpsertBulk) AddFileSize(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateFileSize() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateFileSize()
	})
}

// ClearFileSize clears the value of the "file_size" field.
func (u *AssetUpsertBulk) ClearFileSize() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearFileSize()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *AssetUpsertBulk) SetStorageKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateStorageKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateStorageKey()
	})
}

// SetThumbnailKey sets the "thumbnail_key" field.
func (u *AssetUpsertBulk) SetThumbnailKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetThumbnailKey(v)
	})
}

// UpdateThumbnailKey sets the "thumbnail_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateThumbnailKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateThumbnailKey()
	})
}

// ClearThumbnailKey clears the value of the "thumbnail_key" field.
func (u *AssetUpsertBulk) ClearThumbnailKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearThumbnailKey()
	})
}

// SetMediumKey sets the "medium_key" field.
func (u *AssetUpsertBulk) SetMediumKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetMediumKey(v)
	})
}

// UpdateMediumKey sets the "medium_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateMediumKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMediumKey()
	})
}

// ClearMediumKey clears the value of the "medium_key" field.
func (u *AssetUpsertBulk) ClearMediumKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMediumKey()
	})
}

// SetCurrentVersion sets the "current_version" field.
func (u *AssetUpsertBulk) SetCurrentVersion(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetCurrentVersion(v)
	})
}

// AddCurrentVersion adds v to the "current_version" field.
func (u *AssetUpsertBulk) AddCurrentVersion(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddCurrentVersion(v)
	})
}

// UpdateCurrentVersion sets the "current_version" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateCurrentVersion() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateCurrentVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsertBulk) SetUpdatedAt(v time.Time) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateUpdatedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AssetUpsertBulk) SetDeletedAt(v time.Time) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateDeletedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AssetUpsertBulk) ClearDeletedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *AssetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AssetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
