// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/imageforge/imageforge/ent/generationinput"
	"github.com/imageforge/imageforge/ent/generationjob"
)

// GenerationInputCreate is the builder for creating a GenerationInput entity.
type GenerationInputCreate struct {
	config
	mutation *GenerationInputMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJobID sets the "job_id" field.
func (_c *GenerationInputCreate) SetJobID(v int64) *GenerationInputCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetSourceAssetID sets the "source_asset_id" field.
func (_c *GenerationInputCreate) SetSourceAssetID(v int64) *GenerationInputCreate {
	_c.mutation.SetSourceAssetID(v)
	return _c
}

// SetNillableSourceAssetID sets the "source_asset_id" field if the given value is not nil.
func (_c *GenerationInputCreate) SetNillableSourceAssetID(v *int64) *GenerationInputCreate {
	if v != nil {
		_c.SetSourceAssetID(*v)
	}
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *GenerationInputCreate) SetStorageKey(v string) *GenerationInputCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_c *GenerationInputCreate) SetNillableStorageKey(v *string) *GenerationInputCreate {
	if v != nil {
		_c.SetStorageKey(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *GenerationInputCreate) SetRole(v string) *GenerationInputCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *GenerationInputCreate) SetNillableRole(v *string) *GenerationInputCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GenerationInputCreate) SetCreatedAt(v time.Time) *GenerationInputCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GenerationInputCreate) SetNillableCreatedAt(v *time.Time) *GenerationInputCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetJob sets the "job" edge to the GenerationJob entity.
func (_c *GenerationInputCreate) SetJob(v *GenerationJob) *GenerationInputCreate {
	return _c.SetJobID(v.ID)
}

// Mutation returns the GenerationInputMutation object of the builder.
func (_c *GenerationInputCreate) Mutation() *GenerationInputMutation {
	return _c.mutation
}

// Save creates the GenerationInput in the database.
func (_c *GenerationInputCreate) Save(ctx context.Context) (*GenerationInput, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GenerationInputCreate) SaveX(ctx context.Context) *GenerationInput {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationInputCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationInputCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GenerationInputCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := generationinput.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GenerationInputCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "GenerationInput.job_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GenerationInput.created_at"`)}
	}
	if len(_c.mutation.JobIDs()) == 0 {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required edge "GenerationInput.job"`)}
	}
	return nil
}

func (_c *GenerationInputCreate) sqlSave(ctx context.Context) (*GenerationInput, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GenerationInputCreate) createSpec() (*GenerationInput, *sqlgraph.CreateSpec) {
	var (
		_node = &GenerationInput{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(generationinput.Table, sqlgraph.NewFieldSpec(generationinput.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SourceAssetID(); ok {
		_spec.SetField(generationinput.FieldSourceAssetID, field.TypeInt64, value)
		_node.SourceAssetID = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(generationinput.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(generationinput.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(generationinput.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generationinput.JobTable,
			Columns: []string{generationinput.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationjob.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GenerationInput.Create().
//		SetJobID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GenerationInputUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *GenerationInputCreate) OnConflict(opts ...sql.ConflictOption) *GenerationInputUpsertOne {
	_c.conflict = opts
	return &GenerationInputUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GenerationInput.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GenerationInputCreate) OnConflictColumns(columns ...string) *GenerationInputUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GenerationInputUpsertOne{
		create: _c,
	}
}

type (
	// GenerationInputUpsertOne is the builder for "upsert"-ing
	//  one GenerationInput node.
	GenerationInputUpsertOne struct {
		create *GenerationInputCreate
	}

	// GenerationInputUpsert is the "OnConflict" setter.
	GenerationInputUpsert struct {
		*sql.UpdateSet
	}
)

// SetJobID sets the "job_id" field.
func (u *GenerationInputUpsert) SetJobID(v int64) *GenerationInputUpsert {
	u.Set(generationinput.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *GenerationInputUpsert) UpdateJobID() *GenerationInputUpsert {
	u.SetExcluded(generationinput.FieldJobID)
	return u
}

// SetSourceAssetID sets the "source_asset_id" field.
func (u *GenerationInputUpsert) SetSourceAssetID(v int64) *GenerationInputUpsert {
	u.Set(generationinput.FieldSourceAssetID, v)
	return u
}

// UpdateSourceAssetID sets the "source_asset_id" field to the value that was provided on create.
func (u *GenerationInputUpsert) UpdateSourceAssetID() *GenerationInputUpsert {
	u.SetExcluded(generationinput.FieldSourceAssetID)
	return u
}

// AddSourceAssetID adds v to the "source_asset_id" field.
func (u *GenerationInputUpsert) AddSourceAssetID(v int64) *GenerationInputUpsert {
	u.Add(generationinput.FieldSourceAssetID, v)
	return u
}

// ClearSourceAssetID clears the value of the "source_asset_id" field.
func (u *GenerationInputUpsert) ClearSourceAssetID() *GenerationInputUpsert {
	u.SetNull(generationinput.FieldSourceAssetID)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *GenerationInputUpsert) SetStorageKey(v string) *GenerationInputUpsert {
	u.Set(generationinput.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *GenerationInputUpsert) UpdateStorageKey() *GenerationInputUpsert {
	u.SetExcluded(generationinput.FieldStorageKey)
	return u
}

// ClearStorageKey clears the value of the "storage_key" field.
func (u *GenerationInputUpsert) ClearStorageKey() *GenerationInputUpsert {
	u.SetNull(generationinput.FieldStorageKey)
	return u
}

// SetRole sets the "role" field.
func (u *GenerationInputUpsert) SetRole(v string) *GenerationInputUpsert {
	u.Set(generationinput.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *GenerationInputUpsert) UpdateRole() *GenerationInputUpsert {
	u.SetExcluded(generationinput.FieldRole)
	return u
}

// ClearRole clears the value of the "role" field.
func (u *GenerationInputUpsert) ClearRole() *GenerationInputUpsert {
	u.SetNull(generationinput.FieldRole)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GenerationInput.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GenerationInputUpsertOne) UpdateNewValues() *GenerationInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(generationinput.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GenerationInput.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GenerationInputUpsertOne) Ignore() *GenerationInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GenerationInputUpsertOne) DoNothing() *GenerationInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GenerationInputCreate.OnConflict
// documentation for more info.
func (u *GenerationInputUpsertOne) Update(set func(*GenerationInputUpsert)) *GenerationInputUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GenerationInputUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *GenerationInputUpsertOne) SetJobID(v int64) *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *GenerationInputUpsertOne) UpdateJobID() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateJobID()
	})
}

// SetSourceAssetID sets the "source_asset_id" field.
func (u *GenerationInputUpsertOne) SetSourceAssetID(v int64) *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetSourceAssetID(v)
	})
}

// AddSourceAssetID adds v to the "source_asset_id" field.
func (u *GenerationInputUpsertOne) AddSourceAssetID(v int64) *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.AddSourceAssetID(v)
	})
}

// UpdateSourceAssetID sets the "source_asset_id" field to the value that was provided on create.
func (u *GenerationInputUpsertOne) UpdateSourceAssetID() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateSourceAssetID()
	})
}

// ClearSourceAssetID clears the value of the "source_asset_id" field.
func (u *GenerationInputUpsertOne) ClearSourceAssetID() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.ClearSourceAssetID()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *GenerationInputUpsertOne) SetStorageKey(v string) *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *GenerationInputUpsertOne) UpdateStorageKey() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateStorageKey()
	})
}

// ClearStorageKey clears the value of the "storage_key" field.
func (u *GenerationInputUpsertOne) ClearStorageKey() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.ClearStorageKey()
	})
}

// SetRole sets the "role" field.
func (u *GenerationInputUpsertOne) SetRole(v string) *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *GenerationInputUpsertOne) UpdateRole() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateRole()
	})
}

// ClearRole clears the value of the "role" field.
func (u *GenerationInputUpsertOne) ClearRole() *GenerationInputUpsertOne {
	return u.Update(func(s *GenerationInputUpsert) {
		s.ClearRole()
	})
}

// Exec executes the query.
func (u *GenerationInputUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GenerationInputCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GenerationInputUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GenerationInputUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GenerationInputUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GenerationInputCreateBulk is the builder for creating many GenerationInput entities in bulk.
type GenerationInputCreateBulk struct {
	config
	err      error
	builders []*GenerationInputCreate
	conflict []sql.ConflictOption
}

// Save creates the GenerationInput entities in the database.
func (_c *GenerationInputCreateBulk) Save(ctx context.Context) ([]*GenerationInput, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GenerationInput, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenerationInputMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GenerationInputCreateBulk) SaveX(ctx context.Context) []*GenerationInput {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationInputCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationInputCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GenerationInput.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GenerationInputUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *GenerationInputCreateBulk) OnConflict(opts ...sql.ConflictOption) *GenerationInputUpsertBulk {
	_c.conflict = opts
	return &GenerationInputUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GenerationInput.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GenerationInputCreateBulk) OnConflictColumns(columns ...string) *GenerationInputUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GenerationInputUpsertBulk{
		create: _c,
	}
}

// GenerationInputUpsertBulk is the builder for "upsert"-ing
// a bulk of GenerationInput nodes.
type GenerationInputUpsertBulk struct {
	create *GenerationInputCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GenerationInput.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GenerationInputUpsertBulk) UpdateNewValues() *GenerationInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(generationinput.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GenerationInput.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GenerationInputUpsertBulk) Ignore() *GenerationInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GenerationInputUpsertBulk) DoNothing() *GenerationInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GenerationInputCreateBulk.OnConflict
// documentation for more info.
func (u *GenerationInputUpsertBulk) Update(set func(*GenerationInputUpsert)) *GenerationInputUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GenerationInputUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *GenerationInputUpsertBulk) SetJobID(v int64) *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *GenerationInputUpsertBulk) UpdateJobID() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateJobID()
	})
}

// SetSourceAssetID sets the "source_asset_id" field.
func (u *GenerationInputUpsertBulk) SetSourceAssetID(v int64) *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetSourceAssetID(v)
	})
}

// AddSourceAssetID adds v to the "source_asset_id" field.
func (u *GenerationInputUpsertBulk) AddSourceAssetID(v int64) *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.AddSourceAssetID(v)
	})
}

// UpdateSourceAssetID sets the "source_asset_id" field to the value that was provided on create.
func (u *GenerationInputUpsertBulk) UpdateSourceAssetID() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateSourceAssetID()
	})
}

// ClearSourceAssetID clears the value of the "source_asset_id" field.
func (u *GenerationInputUpsertBulk) ClearSourceAssetID() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.ClearSourceAssetID()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *GenerationInputUpsertBulk) SetStorageKey(v string) *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *GenerationInputUpsertBulk) UpdateStorageKey() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateStorageKey()
	})
}

// ClearStorageKey clears the value of the "storage_key" field.
func (u *GenerationInputUpsertBulk) ClearStorageKey() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.ClearStorageKey()
	})
}

// SetRole sets the "role" field.
func (u *GenerationInputUpsertBulk) SetRole(v string) *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *GenerationInputUpsertBulk) UpdateRole() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.UpdateRole()
	})
}

// ClearRole clears the value of the "role" field.
func (u *GenerationInputUpsertBulk) ClearRole() *GenerationInputUpsertBulk {
	return u.Update(func(s *GenerationInputUpsert) {
		s.ClearRole()
	})
}

// Exec executes the query.
func (u *GenerationInputUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GenerationInputCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GenerationInputCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GenerationInputUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
