// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/imageforge/imageforge/ent/asset"
	"github.com/imageforge/imageforge/ent/generationinput"
	"github.com/imageforge/imageforge/ent/generationjob"
	"github.com/imageforge/imageforge/ent/project"
	"github.com/imageforge/imageforge/ent/user"
)

// GenerationJobCreate is the builder for creating a GenerationJob entity.
type GenerationJobCreate struct {
	config
	mutation *GenerationJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *GenerationJobCreate) SetUserID(v int64) *GenerationJobCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *GenerationJobCreate) SetExternalID(v string) *GenerationJobCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableExternalID(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *GenerationJobCreate) SetProjectID(v int64) *GenerationJobCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableProjectID(v *int64) *GenerationJobCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *GenerationJobCreate) SetType(v generationjob.Type) *GenerationJobCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GenerationJobCreate) SetStatus(v generationjob.Status) *GenerationJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableStatus(v *generationjob.Status) *GenerationJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *GenerationJobCreate) SetProvider(v string) *GenerationJobCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableProvider(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *GenerationJobCreate) SetModel(v string) *GenerationJobCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableModel(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSub2apiTaskID sets the "sub2api_task_id" field.
func (_c *GenerationJobCreate) SetSub2apiTaskID(v string) *GenerationJobCreate {
	_c.mutation.SetSub2apiTaskID(v)
	return _c
}

// SetNillableSub2apiTaskID sets the "sub2api_task_id" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableSub2apiTaskID(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetSub2apiTaskID(*v)
	}
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *GenerationJobCreate) SetPrompt(v string) *GenerationJobCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillablePrompt(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetPrompt(*v)
	}
	return _c
}

// SetNegativePrompt sets the "negative_prompt" field.
func (_c *GenerationJobCreate) SetNegativePrompt(v string) *GenerationJobCreate {
	_c.mutation.SetNegativePrompt(v)
	return _c
}

// SetNillableNegativePrompt sets the "negative_prompt" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableNegativePrompt(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetNegativePrompt(*v)
	}
	return _c
}

// SetAspectRatio sets the "aspect_ratio" field.
func (_c *GenerationJobCreate) SetAspectRatio(v string) *GenerationJobCreate {
	_c.mutation.SetAspectRatio(v)
	return _c
}

// SetNillableAspectRatio sets the "aspect_ratio" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableAspectRatio(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetAspectRatio(*v)
	}
	return _c
}

// SetImageCount sets the "image_count" field.
func (_c *GenerationJobCreate) SetImageCount(v int) *GenerationJobCreate {
	_c.mutation.SetImageCount(v)
	return _c
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableImageCount(v *int) *GenerationJobCreate {
	if v != nil {
		_c.SetImageCount(*v)
	}
	return _c
}

// SetOutputFormat sets the "output_format" field.
func (_c *GenerationJobCreate) SetOutputFormat(v string) *GenerationJobCreate {
	_c.mutation.SetOutputFormat(v)
	return _c
}

// SetNillableOutputFormat sets the "output_format" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableOutputFormat(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetOutputFormat(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *GenerationJobCreate) SetErrorCode(v string) *GenerationJobCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableErrorCode(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *GenerationJobCreate) SetErrorMessage(v string) *GenerationJobCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableErrorMessage(v *string) *GenerationJobCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *GenerationJobCreate) SetRetryCount(v int) *GenerationJobCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableRetryCount(v *int) *GenerationJobCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetBatchImageState sets the "batch_image_state" field.
func (_c *GenerationJobCreate) SetBatchImageState(v map[string]interface{}) *GenerationJobCreate {
	_c.mutation.SetBatchImageState(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *GenerationJobCreate) SetStartedAt(v time.Time) *GenerationJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableStartedAt(v *time.Time) *GenerationJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *GenerationJobCreate) SetCompletedAt(v time.Time) *GenerationJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableCompletedAt(v *time.Time) *GenerationJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GenerationJobCreate) SetCreatedAt(v time.Time) *GenerationJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableCreatedAt(v *time.Time) *GenerationJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GenerationJobCreate) SetUpdatedAt(v time.Time) *GenerationJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GenerationJobCreate) SetNillableUpdatedAt(v *time.Time) *GenerationJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *GenerationJobCreate) SetUser(v *User) *GenerationJobCreate {
	return _c.SetUserID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_c *GenerationJobCreate) SetProject(v *Project) *GenerationJobCreate {
	return _c.SetProjectID(v.ID)
}

// AddInputIDs adds the "inputs" edge to the GenerationInput entity by IDs.
func (_c *GenerationJobCreate) AddInputIDs(ids ...int64) *GenerationJobCreate {
	_c.mutation.AddInputIDs(ids...)
	return _c
}

// AddInputs adds the "inputs" edges to the GenerationInput entity.
func (_c *GenerationJobCreate) AddInputs(v ...*GenerationInput) *GenerationJobCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInputIDs(ids...)
}

// AddOutputAssetIDs adds the "output_assets" edge to the Asset entity by IDs.
func (_c *GenerationJobCreate) AddOutputAssetIDs(ids ...int64) *GenerationJobCreate {
	_c.mutation.AddOutputAssetIDs(ids...)
	return _c
}

// AddOutputAssets adds the "output_assets" edges to the Asset entity.
func (_c *GenerationJobCreate) AddOutputAssets(v ...*Asset) *GenerationJobCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOutputAssetIDs(ids...)
}

// Mutation returns the GenerationJobMutation object of the builder.
func (_c *GenerationJobCreate) Mutation() *GenerationJobMutation {
	return _c.mutation
}

// Save creates the GenerationJob in the database.
func (_c *GenerationJobCreate) Save(ctx context.Context) (*GenerationJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GenerationJobCreate) SaveX(ctx context.Context) *GenerationJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GenerationJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := generationjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		v := generationjob.DefaultImageCount
		_c.mutation.SetImageCount(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := generationjob.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.BatchImageState(); !ok {
		v := generationjob.DefaultBatchImageState
		_c.mutation.SetBatchImageState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := generationjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := generationjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GenerationJobCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "GenerationJob.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "GenerationJob.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := generationjob.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "GenerationJob.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GenerationJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := generationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GenerationJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		return &ValidationError{Name: "image_count", err: errors.New(`ent: missing required field "GenerationJob.image_count"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "GenerationJob.retry_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GenerationJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GenerationJob.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "GenerationJob.user"`)}
	}
	return nil
}

func (_c *GenerationJobCreate) sqlSave(ctx context.Context) (*GenerationJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GenerationJobCreate) createSpec() (*GenerationJob, *sqlgraph.CreateSpec) {
	var (
		_node = &GenerationJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(generationjob.Table, sqlgraph.NewFieldSpec(generationjob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(generationjob.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(generationjob.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(generationjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(generationjob.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(generationjob.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Sub2apiTaskID(); ok {
		_spec.SetField(generationjob.FieldSub2apiTaskID, field.TypeString, value)
		_node.Sub2apiTaskID = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(generationjob.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.NegativePrompt(); ok {
		_spec.SetField(generationjob.FieldNegativePrompt, field.TypeString, value)
		_node.NegativePrompt = value
	}
	if value, ok := _c.mutation.AspectRatio(); ok {
		_spec.SetField(generationjob.FieldAspectRatio, field.TypeString, value)
		_node.AspectRatio = value
	}
	if value, ok := _c.mutation.ImageCount(); ok {
		_spec.SetField(generationjob.FieldImageCount, field.TypeInt, value)
		_node.ImageCount = value
	}
	if value, ok := _c.mutation.OutputFormat(); ok {
		_spec.SetField(generationjob.FieldOutputFormat, field.TypeString, value)
		_node.OutputFormat = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(generationjob.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(generationjob.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(generationjob.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.BatchImageState(); ok {
		_spec.SetField(generationjob.FieldBatchImageState, field.TypeJSON, value)
		_node.BatchImageState = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(generationjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(generationjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(generationjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(generationjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generationjob.UserTable,
			Columns: []string{generationjob.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generationjob.ProjectTable,
			Columns: []string{generationjob.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InputsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationjob.InputsTable,
			Columns: []string{generationjob.InputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationinput.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OutputAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationjob.OutputAssetsTable,
			Columns: []string{generationjob.OutputAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GenerationJob.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GenerationJobUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *GenerationJobCreate) OnConflict(opts ...sql.ConflictOption) *GenerationJobUpsertOne {
	_c.conflict = opts
	return &GenerationJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GenerationJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GenerationJobCreate) OnConflictColumns(columns ...string) *GenerationJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GenerationJobUpsertOne{
		create: _c,
	}
}

type (
	// GenerationJobUpsertOne is the builder for "upsert"-ing
	//  one GenerationJob node.
	GenerationJobUpsertOne struct {
		create *GenerationJobCreate
	}

	// GenerationJobUpsert is the "OnConflict" setter.
	GenerationJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *GenerationJobUpsert) SetUserID(v int64) *GenerationJobUpsert {
	u.Set(generationjob.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateUserID() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldUserID)
	return u
}

// SetExternalID sets the "external_id" field.
func (u *GenerationJobUpsert) SetExternalID(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldExternalID, v)
	return u
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateExternalID() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldExternalID)
	return u
}

// ClearExternalID clears the value of the "external_id" field.
func (u *GenerationJobUpsert) ClearExternalID() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldExternalID)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *GenerationJobUpsert) SetProjectID(v int64) *GenerationJobUpsert {
	u.Set(generationjob.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateProjectID() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldProjectID)
	return u
}

// ClearProjectID clears the value of the "project_id" field.
func (u *GenerationJobUpsert) ClearProjectID() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldProjectID)
	return u
}

// SetStatus sets the "status" field.
func (u *GenerationJobUpsert) SetStatus(v generationjob.Status) *GenerationJobUpsert {
	u.Set(generationjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateStatus() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldStatus)
	return u
}

// SetProvider sets the "provider" field.
func (u *GenerationJobUpsert) SetProvider(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateProvider() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *GenerationJobUpsert) ClearProvider() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *GenerationJobUpsert) SetModel(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateModel() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *GenerationJobUpsert) ClearModel() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldModel)
	return u
}

// SetSub2apiTaskID sets the "sub2api_task_id" field.
func (u *GenerationJobUpsert) SetSub2apiTaskID(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldSub2apiTaskID, v)
	return u
}

// UpdateSub2apiTaskID sets the "sub2api_task_id" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateSub2apiTaskID() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldSub2apiTaskID)
	return u
}

// ClearSub2apiTaskID clears the value of the "sub2api_task_id" field.
func (u *GenerationJobUpsert) ClearSub2apiTaskID() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldSub2apiTaskID)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *GenerationJobUpsert) SetPrompt(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdatePrompt() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldPrompt)
	return u
}

// ClearPrompt clears the value of the "prompt" field.
func (u *GenerationJobUpsert) ClearPrompt() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldPrompt)
	return u
}

// SetNegativePrompt sets the "negative_prompt" field.
func (u *GenerationJobUpsert) SetNegativePrompt(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldNegativePrompt, v)
	return u
}

// UpdateNegativePrompt sets the "negative_prompt" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateNegativePrompt() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldNegativePrompt)
	return u
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (u *GenerationJobUpsert) ClearNegativePrompt() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldNegativePrompt)
	return u
}

// SetAspectRatio sets the "aspect_ratio" field.
func (u *GenerationJobUpsert) SetAspectRatio(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldAspectRatio, v)
	return u
}

// UpdateAspectRatio sets the "aspect_ratio" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateAspectRatio() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldAspectRatio)
	return u
}

// ClearAspectRatio clears the value of the "aspect_ratio" field.
func (u *GenerationJobUpsert) ClearAspectRatio() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldAspectRatio)
	return u
}

// SetImageCount sets the "image_count" field.
func (u *GenerationJobUpsert) SetImageCount(v int) *GenerationJobUpsert {
	u.Set(generationjob.FieldImageCount, v)
	return u
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateImageCount() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldImageCount)
	return u
}

// AddImageCount adds v to the "image_count" field.
func (u *GenerationJobUpsert) AddImageCount(v int) *GenerationJobUpsert {
	u.Add(generationjob.FieldImageCount, v)
	return u
}

// SetOutputFormat sets the "output_format" field.
func (u *GenerationJobUpsert) SetOutputFormat(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldOutputFormat, v)
	return u
}

// UpdateOutputFormat sets the "output_format" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateOutputFormat() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldOutputFormat)
	return u
}

// ClearOutputFormat clears the value of the "output_format" field.
func (u *GenerationJobUpsert) ClearOutputFormat() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldOutputFormat)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *GenerationJobUpsert) SetErrorCode(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateErrorCode() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *GenerationJobUpsert) ClearErrorCode() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *GenerationJobUpsert) SetErrorMessage(v string) *GenerationJobUpsert {
	u.Set(generationjob.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateErrorMessage() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *GenerationJobUpsert) ClearErrorMessage() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldErrorMessage)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *GenerationJobUpsert) SetRetryCount(v int) *GenerationJobUpsert {
	u.Set(generationjob.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateRetryCount() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *GenerationJobUpsert) AddRetryCount(v int) *GenerationJobUpsert {
	u.Add(generationjob.FieldRetryCount, v)
	return u
}

// SetBatchImageState sets the "batch_image_state" field.
func (u *GenerationJobUpsert) SetBatchImageState(v map[string]interface{}) *GenerationJobUpsert {
	u.Set(generationjob.FieldBatchImageState, v)
	return u
}

// UpdateBatchImageState sets the "batch_image_state" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateBatchImageState() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldBatchImageState)
	return u
}

// ClearBatchImageState clears the value of the "batch_image_state" field.
func (u *GenerationJobUpsert) ClearBatchImageState() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldBatchImageState)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *GenerationJobUpsert) SetStartedAt(v time.Time) *GenerationJobUpsert {
	u.Set(generationjob.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateStartedAt() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *GenerationJobUpsert) ClearStartedAt() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *GenerationJobUpsert) SetCompletedAt(v time.Time) *GenerationJobUpsert {
	u.Set(generationjob.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateCompletedAt() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *GenerationJobUpsert) ClearCompletedAt() *GenerationJobUpsert {
	u.SetNull(generationjob.FieldCompletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GenerationJobUpsert) SetUpdatedAt(v time.Time) *GenerationJobUpsert {
	u.Set(generationjob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GenerationJobUpsert) UpdateUpdatedAt() *GenerationJobUpsert {
	u.SetExcluded(generationjob.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GenerationJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GenerationJobUpsertOne) UpdateNewValues() *GenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.GetType(); exists {
			s.SetIgnore(generationjob.FieldType)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(generationjob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GenerationJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GenerationJobUpsertOne) Ignore() *GenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GenerationJobUpsertOne) DoNothing() *GenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GenerationJobCreate.OnConflict
// documentation for more info.
func (u *GenerationJobUpsertOne) Update(set func(*GenerationJobUpsert)) *GenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GenerationJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *GenerationJobUpsertOne) SetUserID(v int64) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateUserID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateUserID()
	})
}

// SetExternalID sets the "external_id" field.
func (u *GenerationJobUpsertOne) SetExternalID(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateExternalID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *GenerationJobUpsertOne) ClearExternalID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearExternalID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *GenerationJobUpsertOne) SetProjectID(v int64) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateProjectID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *GenerationJobUpsertOne) ClearProjectID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearProjectID()
	})
}

// SetStatus sets the "status" field.
func (u *GenerationJobUpsertOne) SetStatus(v generationjob.Status) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateStatus() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *GenerationJobUpsertOne) SetProvider(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateProvider() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *GenerationJobUpsertOne) ClearProvider() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearProvider()
	})
}

// SetModel sets the "model" field.
func (u *GenerationJobUpsertOne) SetModel(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateModel() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *GenerationJobUpsertOne) ClearModel() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearModel()
	})
}

// SetSub2apiTaskID sets the "sub2api_task_id" field.
func (u *GenerationJobUpsertOne) SetSub2apiTaskID(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetSub2apiTaskID(v)
	})
}

// UpdateSub2apiTaskID sets the "sub2api_task_id" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateSub2apiTaskID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateSub2apiTaskID()
	})
}

// ClearSub2apiTaskID clears the value of the "sub2api_task_id" field.
func (u *GenerationJobUpsertOne) ClearSub2apiTaskID() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearSub2apiTaskID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *GenerationJobUpsertOne) SetPrompt(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdatePrompt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdatePrompt()
	})
}

// ClearPrompt clears the value of the "prompt" field.
func (u *GenerationJobUpsertOne) ClearPrompt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearPrompt()
	})
}

// SetNegativePrompt sets the "negative_prompt" field.
func (u *GenerationJobUpsertOne) SetNegativePrompt(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetNegativePrompt(v)
	})
}

// UpdateNegativePrompt sets the "negative_prompt" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateNegativePrompt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateNegativePrompt()
	})
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (u *GenerationJobUpsertOne) ClearNegativePrompt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearNegativePrompt()
	})
}

// SetAspectRatio sets the "aspect_ratio" field.
func (u *GenerationJobUpsertOne) SetAspectRatio(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetAspectRatio(v)
	})
}

// UpdateAspectRatio sets the "aspect_ratio" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateAspectRatio() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateAspectRatio()
	})
}

// ClearAspectRatio clears the value of the "aspect_ratio" field.
func (u *GenerationJobUpsertOne) ClearAspectRatio() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearAspectRatio()
	})
}

// SetImageCount sets the "image_count" field.
func (u *GenerationJobUpsertOne) SetImageCount(v int) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *GenerationJobUpsertOne) AddImageCount(v int) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateImageCount() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateImageCount()
	})
}

// SetOutputFormat sets the "output_format" field.
func (u *GenerationJobUpsertOne) SetOutputFormat(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetOutputFormat(v)
	})
}

// UpdateOutputFormat sets the "output_format" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateOutputFormat() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateOutputFormat()
	})
}

// ClearOutputFormat clears the value of the "output_format" field.
func (u *GenerationJobUpsertOne) ClearOutputFormat() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearOutputFormat()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *GenerationJobUpsertOne) SetErrorCode(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateErrorCode() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *GenerationJobUpsertOne) ClearErrorCode() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *GenerationJobUpsertOne) SetErrorMessage(v string) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateErrorMessage() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *GenerationJobUpsertOne) ClearErrorMessage() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *GenerationJobUpsertOne) SetRetryCount(v int) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *GenerationJobUpsertOne) AddRetryCount(v int) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateRetryCount() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateRetryCount()
	})
}

// SetBatchImageState sets the "batch_image_state" field.
func (u *GenerationJobUpsertOne) SetBatchImageState(v map[string]interface{}) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetBatchImageState(v)
	})
}

// UpdateBatchImageState sets the "batch_image_state" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateBatchImageState() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateBatchImageState()
	})
}

// ClearBatchImageState clears the value of the "batch_image_state" field.
func (u *GenerationJobUpsertOne) ClearBatchImageState() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearBatchImageState()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *GenerationJobUpsertOne) SetStartedAt(v time.Time) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateStartedAt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *GenerationJobUpsertOne) ClearStartedAt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *GenerationJobUpsertOne) SetCompletedAt(v time.Time) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateCompletedAt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *GenerationJobUpsertOne) ClearCompletedAt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GenerationJobUpsertOne) SetUpdatedAt(v time.Time) *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GenerationJobUpsertOne) UpdateUpdatedAt() *GenerationJobUpsertOne {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GenerationJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GenerationJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GenerationJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GenerationJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GenerationJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GenerationJobCreateBulk is the builder for creating many GenerationJob entities in bulk.
type GenerationJobCreateBulk struct {
	config
	err      error
	builders []*GenerationJobCreate
	conflict []sql.ConflictOption
}

// Save creates the GenerationJob entities in the database.
func (_c *GenerationJobCreateBulk) Save(ctx context.Context) ([]*GenerationJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GenerationJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenerationJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GenerationJobCreateBulk) SaveX(ctx context.Context) []*GenerationJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GenerationJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GenerationJobUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *GenerationJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *GenerationJobUpsertBulk {
	_c.conflict = opts
	return &GenerationJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GenerationJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GenerationJobCreateBulk) OnConflictColumns(columns ...string) *GenerationJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GenerationJobUpsertBulk{
		create: _c,
	}
}

// GenerationJobUpsertBulk is the builder for "upsert"-ing
// a bulk of GenerationJob nodes.
type GenerationJobUpsertBulk struct {
	create *GenerationJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GenerationJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GenerationJobUpsertBulk) UpdateNewValues() *GenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.GetType(); exists {
				s.SetIgnore(generationjob.FieldType)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(generationjob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GenerationJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GenerationJobUpsertBulk) Ignore() *GenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GenerationJobUpsertBulk) DoNothing() *GenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GenerationJobCreateBulk.OnConflict
// documentation for more info.
func (u *GenerationJobUpsertBulk) Update(set func(*GenerationJobUpsert)) *GenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GenerationJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *GenerationJobUpsertBulk) SetUserID(v int64) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateUserID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateUserID()
	})
}

// SetExternalID sets the "external_id" field.
func (u *GenerationJobUpsertBulk) SetExternalID(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateExternalID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *GenerationJobUpsertBulk) ClearExternalID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearExternalID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *GenerationJobUpsertBulk) SetProjectID(v int64) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateProjectID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *GenerationJobUpsertBulk) ClearProjectID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearProjectID()
	})
}

// SetStatus sets the "status" field.
func (u *GenerationJobUpsertBulk) SetStatus(v generationjob.Status) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateStatus() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *GenerationJobUpsertBulk) SetProvider(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateProvider() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *GenerationJobUpsertBulk) ClearProvider() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearProvider()
	})
}

// SetModel sets the "model" field.
func (u *GenerationJobUpsertBulk) SetModel(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateModel() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *GenerationJobUpsertBulk) ClearModel() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearModel()
	})
}

// SetSub2apiTaskID sets the "sub2api_task_id" field.
func (u *GenerationJobUpsertBulk) SetSub2apiTaskID(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetSub2apiTaskID(v)
	})
}

// UpdateSub2apiTaskID sets the "sub2api_task_id" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateSub2apiTaskID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateSub2apiTaskID()
	})
}

// ClearSub2apiTaskID clears the value of the "sub2api_task_id" field.
func (u *GenerationJobUpsertBulk) ClearSub2apiTaskID() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearSub2apiTaskID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *GenerationJobUpsertBulk) SetPrompt(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdatePrompt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdatePrompt()
	})
}

// ClearPrompt clears the value of the "prompt" field.
func (u *GenerationJobUpsertBulk) ClearPrompt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearPrompt()
	})
}

// SetNegativePrompt sets the "negative_prompt" field.
func (u *GenerationJobUpsertBulk) SetNegativePrompt(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetNegativePrompt(v)
	})
}

// UpdateNegativePrompt sets the "negative_prompt" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateNegativePrompt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateNegativePrompt()
	})
}

// ClearNegativePrompt clears the value of the "negative_prompt" field.
func (u *GenerationJobUpsertBulk) ClearNegativePrompt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearNegativePrompt()
	})
}

// SetAspectRatio sets the "aspect_ratio" field.
func (u *GenerationJobUpsertBulk) SetAspectRatio(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetAspectRatio(v)
	})
}

// UpdateAspectRatio sets the "aspect_ratio" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateAspectRatio() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateAspectRatio()
	})
}

// ClearAspectRatio clears the value of the "aspect_ratio" field.
func (u *GenerationJobUpsertBulk) ClearAspectRatio() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearAspectRatio()
	})
}

// SetImageCount sets the "image_count" field.
func (u *GenerationJobUpsertBulk) SetImageCount(v int) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *GenerationJobUpsertBulk) AddImageCount(v int) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateImageCount() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateImageCount()
	})
}

// SetOutputFormat sets the "output_format" field.
func (u *GenerationJobUpsertBulk) SetOutputFormat(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetOutputFormat(v)
	})
}

// UpdateOutputFormat sets the "output_format" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateOutputFormat() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateOutputFormat()
	})
}

// ClearOutputFormat clears the value of the "output_format" field.
func (u *GenerationJobUpsertBulk) ClearOutputFormat() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearOutputFormat()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *GenerationJobUpsertBulk) SetErrorCode(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateErrorCode() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *GenerationJobUpsertBulk) ClearErrorCode() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *GenerationJobUpsertBulk) SetErrorMessage(v string) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateErrorMessage() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *GenerationJobUpsertBulk) ClearErrorMessage() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *GenerationJobUpsertBulk) SetRetryCount(v int) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *GenerationJobUpsertBulk) AddRetryCount(v int) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateRetryCount() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateRetryCount()
	})
}

// SetBatchImageState sets the "batch_image_state" field.
func (u *GenerationJobUpsertBulk) SetBatchImageState(v map[string]interface{}) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetBatchImageState(v)
	})
}

// UpdateBatchImageState sets the "batch_image_state" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateBatchImageState() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateBatchImageState()
	})
}

// ClearBatchImageState clears the value of the "batch_image_state" field.
func (u *GenerationJobUpsertBulk) ClearBatchImageState() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearBatchImageState()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *GenerationJobUpsertBulk) SetStartedAt(v time.Time) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateStartedAt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *GenerationJobUpsertBulk) ClearStartedAt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *GenerationJobUpsertBulk) SetCompletedAt(v time.Time) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateCompletedAt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *GenerationJobUpsertBulk) ClearCompletedAt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GenerationJobUpsertBulk) SetUpdatedAt(v time.Time) *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GenerationJobUpsertBulk) UpdateUpdatedAt() *GenerationJobUpsertBulk {
	return u.Update(func(s *GenerationJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GenerationJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GenerationJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GenerationJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GenerationJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
