// Package service holds the business-logic layer. AssetService owns asset CRUD,
// immutable versioning, and content serving. Every binary lives in object
// storage; the DB stores only keys and metadata.
package service

import (
	"context"
	"io"

	"github.com/imageforge/imageforge/ent"
	"github.com/imageforge/imageforge/ent/asset"
	"github.com/imageforge/imageforge/ent/assetversion"
	"github.com/imageforge/imageforge/ent/generationjob"
	"github.com/imageforge/imageforge/ent/tag"
	"github.com/imageforge/imageforge/internal/pkg/errors"
	"github.com/imageforge/imageforge/internal/storage"
)

// StorageKeys holds the object-storage keys for a single image asset. The
// original is required; thumbnail/medium are optional renditions generated by
// the thumbnail pipeline.
type StorageKeys struct {
	Original  string
	Thumbnail string
	Medium    string
}

// AssetService handles asset CRUD, versioning, and content serving.
type AssetService struct {
	db    *ent.Client
	store storage.Storage
}

// NewAssetService builds an AssetService.
func NewAssetService(db *ent.Client, store storage.Storage) *AssetService {
	return &AssetService{db: db, store: store}
}

// AssetFilter is the filter for listing assets.
type AssetFilter struct {
	ProjectID string
	Tag       string
	Page      int
	PageSize  int
}

// CreateFromGeneration creates an Asset plus its initial (version 1) AssetVersion
// in a single transaction, linking the asset to the generation job that
// produced it. The jobID is the job's external_id. Thumbnail/medium keys are
// optional and recorded when present.
func (s *AssetService) CreateFromGeneration(ctx context.Context, jobID string, userID int64, projectID *int64, prompt, model string, keys StorageKeys) (*ent.Asset, error) {
	if keys.Original == "" {
		return nil, errors.New(errors.ErrInvalidRequest, "original storage key is required")
	}

	job, err := s.db.GenerationJob.Query().
		Where(generationjob.ExternalID(jobID)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, errors.New(errors.ErrNotFound, "generation job not found")
		}
		return nil, errors.Wrap(errors.ErrInternal, "failed to fetch generation job", err)
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to start transaction", err)
	}
	defer tx.Rollback()

	ac := tx.Client().Asset.Create().
		SetUserID(userID).
		SetSource(asset.SourceGenerated).
		SetStatus(asset.StatusActive).
		SetPrompt(prompt).
		SetModel(model).
		SetStorageKey(keys.Original).
		SetCurrentVersion(1).
		SetGenerationJobID(job.ID)
	if projectID != nil {
		ac = ac.SetNillableProjectID(projectID)
	}
	if keys.Thumbnail != "" {
		ac = ac.SetThumbnailKey(keys.Thumbnail)
	}
	if keys.Medium != "" {
		ac = ac.SetMediumKey(keys.Medium)
	}
	created, err := ac.Save(ctx)
	if err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to create asset", err)
	}

	if _, err := tx.Client().AssetVersion.Create().
		SetAssetID(created.ID).
		SetVersion(1).
		SetPrompt(prompt).
		SetModel(model).
		SetStorageKey(keys.Original).
		SetNillableThumbnailKey(nilIfEmpty(keys.Thumbnail)).
		Save(ctx); err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to create initial asset version", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to commit transaction", err)
	}
	return created, nil
}

// CreateVersion appends a new immutable version to an existing asset and bumps
// the asset's current_version counter, all in one transaction. editJobID may be
// nil for uploads or manual edits.
func (s *AssetService) CreateVersion(ctx context.Context, assetID int64, editJobID *int64, prompt, model string, keys StorageKeys) (*ent.AssetVersion, error) {
	if keys.Original == "" {
		return nil, errors.New(errors.ErrInvalidRequest, "original storage key is required")
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to start transaction", err)
	}
	defer tx.Rollback()

	a, err := tx.Client().Asset.Query().
		Where(asset.ID(assetID)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, errors.New(errors.ErrNotFound, "asset not found")
		}
		return nil, errors.Wrap(errors.ErrInternal, "failed to fetch asset", err)
	}

	next := a.CurrentVersion + 1

	ver, err := tx.Client().AssetVersion.Create().
		SetAssetID(assetID).
		SetVersion(next).
		SetNillableEditJobID(editJobID).
		SetPrompt(prompt).
		SetModel(model).
		SetStorageKey(keys.Original).
		SetNillableThumbnailKey(nilIfEmpty(keys.Thumbnail)).
		Save(ctx)
	if err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to create asset version", err)
	}

	if _, err := tx.Client().Asset.UpdateOneID(assetID).
		SetCurrentVersion(next).
		Save(ctx); err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to bump asset version", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to commit transaction", err)
	}
	return ver, nil
}

// GetContent returns the raw image bytes for an asset. When version is nil the
// asset's current original is served; otherwise the requested immutable version
// is served. Ownership is enforced via Get.
func (s *AssetService) GetContent(ctx context.Context, assetID int64, userID int64, version *int) ([]byte, string, error) {
	a, err := s.Get(ctx, assetID, userID)
	if err != nil {
		return nil, "", err
	}

	storageKey := a.StorageKey
	mimeType := a.MimeType
	if version != nil {
		ver, err := s.db.AssetVersion.Query().
			Where(assetversion.AssetIDEQ(assetID), assetversion.VersionEQ(*version)).
			Only(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, "", errors.New(errors.ErrNotFound, "version not found")
			}
			return nil, "", errors.Wrap(errors.ErrInternal, "failed to fetch version", err)
		}
		storageKey = ver.StorageKey
		if ver.MimeType != "" {
			mimeType = ver.MimeType
		}
	}

	if storageKey == "" {
		return nil, "", errors.New(errors.ErrNotFound, "no content available for asset")
	}

	rc, err := s.store.Get(ctx, storageKey)
	if err != nil {
		return nil, "", errors.Wrap(errors.ErrInternal, "failed to read content from storage", err)
	}
	defer rc.Close()

	data, err := io.ReadAll(rc)
	if err != nil {
		return nil, "", errors.Wrap(errors.ErrInternal, "failed to read content", err)
	}
	return data, mimeType, nil
}

// GetContentReader returns a reader for the asset content.
// The caller is responsible for closing the returned reader.
// This is more memory-efficient for large files than GetContent.
func (s *AssetService) GetContentReader(ctx context.Context, assetID int64, userID int64, version *int) (io.ReadCloser, string, error) {
	a, err := s.Get(ctx, assetID, userID)
	if err != nil {
		return nil, "", err
	}

	storageKey := a.StorageKey
	mimeType := a.MimeType
	if version != nil {
		ver, err := s.db.AssetVersion.Query().
			Where(assetversion.AssetIDEQ(assetID), assetversion.VersionEQ(*version)).
			Only(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, "", errors.New(errors.ErrNotFound, "version not found")
			}
			return nil, "", errors.Wrap(errors.ErrInternal, "failed to fetch version", err)
		}
		storageKey = ver.StorageKey
		if ver.MimeType != "" {
			mimeType = ver.MimeType
		}
	}

	if storageKey == "" {
		return nil, "", errors.New(errors.ErrNotFound, "no content available for asset")
	}

	rc, err := s.store.Get(ctx, storageKey)
	if err != nil {
		return nil, "", errors.Wrap(errors.ErrInternal, "failed to read content from storage", err)
	}
	return rc, mimeType, nil
}

// ListVersions returns the version history of an asset (oldest first) after
// enforcing ownership.
func (s *AssetService) ListVersions(ctx context.Context, assetID int64, userID int64) ([]*ent.AssetVersion, error) {
	if _, err := s.Get(ctx, assetID, userID); err != nil {
		return nil, err
	}

	versions, err := s.db.AssetVersion.Query().
		Where(assetversion.AssetIDEQ(assetID)).
		Order(assetversion.ByVersion()).
		All(ctx)
	if err != nil {
		return nil, errors.Wrap(errors.ErrInternal, "failed to list versions", err)
	}
	return versions, nil
}

// GetVersion returns a single version by asset + version number, enforcing
// asset ownership.
func (s *AssetService) GetVersion(ctx context.Context, assetID int64, version int, userID int64) (*ent.AssetVersion, error) {
	if _, err := s.Get(ctx, assetID, userID); err != nil {
		return nil, err
	}

	ver, err := s.db.AssetVersion.Query().
		Where(assetversion.AssetIDEQ(assetID), assetversion.VersionEQ(version)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, errors.New(errors.ErrNotFound, "version not found")
		}
		return nil, errors.Wrap(errors.ErrInternal, "failed to fetch version", err)
	}
	return ver, nil
}

// List returns assets for a user with filtering and pagination.
func (s *AssetService) List(ctx context.Context, userID int64, filter AssetFilter) ([]*ent.Asset, int, error) {
	query := s.db.Asset.Query().
		Where(asset.UserID(userID))

	if filter.ProjectID != "" {
		pid, err := parseInt(filter.ProjectID)
		if err == nil {
			query = query.Where(asset.ProjectID(pid))
		}
	}

	if filter.Tag != "" {
		query = query.Where(asset.HasTagsWith(tag.Name(filter.Tag)))
	}

	if filter.PageSize <= 0 || filter.PageSize > 100 {
		filter.PageSize = 20
	}
	if filter.Page <= 0 {
		filter.Page = 1
	}

	total, err := query.Count(ctx)
	if err != nil {
		return nil, 0, errors.Wrap(errors.ErrInternal, "failed to count assets", err)
	}

	assets, err := query.
		Order(ent.Desc(asset.FieldCreatedAt)).
		Limit(filter.PageSize).
		Offset((filter.Page - 1) * filter.PageSize).
		All(ctx)
	if err != nil {
		return nil, 0, errors.Wrap(errors.ErrInternal, "failed to list assets", err)
	}
	return assets, total, nil
}

// Get returns an asset by ID, enforcing ownership.
func (s *AssetService) Get(ctx context.Context, assetID int64, userID int64) (*ent.Asset, error) {
	a, err := s.db.Asset.Query().
		Where(asset.ID(assetID)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, errors.New(errors.ErrNotFound, "asset not found")
		}
		return nil, errors.Wrap(errors.ErrInternal, "failed to fetch asset", err)
	}
	if a.UserID != userID {
		return nil, errors.New(errors.ErrForbidden, "access denied")
	}
	return a, nil
}

// Delete soft-deletes an asset.
func (s *AssetService) Delete(ctx context.Context, assetID int64, userID int64) error {
	a, err := s.Get(ctx, assetID, userID)
	if err != nil {
		return err
	}
	_, err = s.db.Asset.UpdateOneID(a.ID).
		SetStatus("deleted").
		Save(ctx)
	return err
}

// nilIfEmpty returns nil for an empty string, otherwise a pointer to the value.
func nilIfEmpty(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}
